### ISSUE TITLE
Layer Manager Issue- On Loading MJML 

### ISSUE THREAD

**Issue by noumanullah** [artf/grapesjs-mjml#10]
Hi 

I am facing a weird issue on loading some mjml created by editor.
Basically it was nesting layers inside image and hence those nested elements like Text, social are not appearing on editor.

And I need to fix every time by using layer manager. Please find attached image to get better idea.
![layermanager](https://user-images.githubusercontent.com/7146752/29827133-8ce9cff6-8cf2-11e7-9a69-96d2495863f1.PNG)

Thank you,
Nouman

**Comment by julienchazal** [comment]
Hello
i get the same problem when i tried to create a custom block like this : 
```
bm.add('mj-2-columns', {
    label: 'Section uep',
    content: `
      <mj-section>
        <mj-column>
          <mj-image src="http://placehold.it/350x250/78c5d6/fff" />
          <mj-text>Content 1</mj-text>
        </mj-column>
        <mj-column>
          <mj-image src="http://placehold.it/350x250/78c5d6/fff" />
          <mj-text>Content 2</mj-text>
        </mj-column>
      </mj-section>`,
    attributes: {
      class: 'gjs-fonts gjs-f-b2',
      // Workaround
      'data-type': 'mj-section',
    },
  });
```

The text is nested inside the image : 
![image](https://user-images.githubusercontent.com/1155648/30591236-3d7e7362-9d42-11e7-923a-e8644c1bae86.png)

PS: i just cloned the grapejs-mjml repo today

**Comment by artf** [comment]
@julienchazal update grapesjs first (not just grapesjs-mjml)

**Comment by julienchazal** [comment]
@artf same with v0.10.6

**Comment by artf** [comment]
Unfortunately, it seems related to the fact HTML5 doesn't accept custom void elements so you have to close the `mj-image` tag (eg. `<mj-image src="..."></mj-image>`). Can't do much about it currently
More info about it:
https://stackoverflow.com/questions/17700179/can-you-define-your-own-self-closing-tag-in-html5
https://stackoverflow.com/questions/3558119/are-non-void-self-closing-tags-valid-in-html5
http://w3c.github.io/html/single-page.html#void-elements

**Comment by kickbk** [comment]
Would really appreciate some type of solution. Totally ok to use regular closing tags, but as soon as you do editor.getHtml, it removes the closing tags. Very frustrating. This is the only major issues we are facing right now.
How do we go about keeping regular closing tags? Is there a way to getHtml but keep the and other self closing tags? @artf ?

**Comment by andresmgsl** [comment]
Any update on this? Like @kickbk said, the **editor.getHtml** removes the closing tag.

**Comment by artf** [comment]
Update the custom `mj-image` component and inside `defaults` of its model put `void: false,`
