### ISSUE TITLE
Liste Import Event

### ISSUE THREAD

**Issue by FlashPapa** [artf/grapesjs-mjml#104]
Hi all !
How can we listen 'before import mjml' ?
To test if there is <mjml> & <mj-body> exist in code imported ?
Thanks

**Comment by DRoet** [comment]
In the v0.2.3 release you can now listen for the import event

```
editor.on('run:mjml-import:change', (mjml) => {
  console.log(mjml);
})
```

hopefully this covers this use case

**Comment by karlitaviky811** [comment]
Hi, I'm using the latest version of grapesjsmjml and this solution doesn't work for me. I need to listen to the event when importing, can someone help me?
