### ISSUE TITLE
[Question] Attributes are removed On Load and preview

### ISSUE THREAD

**Issue by sdrebel** [artf/grapesjs-mjml#106]
Hi @artf ,

I'm not able to see attributes on load of the page But if I check the code manager or using editor.getHtml() then I can see the  attributes for the component. 

If I select the component and update the trait's value then it will be added.

Is there anyway to to see in the editor? Because of this issue if i'm targeting any events using attributes, those are not working. 

Screenshot from the editor
![attributes1](https://user-images.githubusercontent.com/19382262/60590320-53af0380-9db9-11e9-8955-2a5f371bc370.jpg)

Screenshot from the code manager
![attributes2](https://user-images.githubusercontent.com/19382262/60590319-53af0380-9db9-11e9-81cd-e83a16f6eed2.jpg)

**Comment by DRoet** [comment]
Could you please provide a more extensive reproduction?
