### ISSUE TITLE
Backbone.undoManager is not constructor

### ISSUE THREAD

**Issue by kavikaran** [artf/grapesjs-mjml#11]
`TypeError: Backbone.UndoManager is not a constructor
    at N.d.initUndoManager (grapes.min.js:17)
    at Object.onLoad (grapes.min.js:15)
    at grapes.min.js:17
    at Array.forEach (<anonymous>)
    at N.d.initialize (grapes.min.js:17)
    at N.d.b.Model (grapes.min.js:2)
    at new N.d (grapes.min.js:3)
    at new b (grapes.min.js:17)
    at Object.init (grapes.min.js:17)
    at VueComponent.mounted (234:8)`

when i disable undoManager still it gives same error.

**Comment by artf** [comment]
Sorry but can't reproduce it, are you using the last version of grapesjs?

**Comment by kavikaran** [comment]
Yes, I'm using the latest version of GrapesJs(The MJML repo: https://github.com/artf/grapesjs-mjml)

**Comment by artf** [comment]
Can you post here your code please?

**Comment by kavikaran** [comment]
Here is my code:
```
editor = grapesjs.init({
      height: '100%',
      noticeOnUnload: 0,
      storageManager:{autoload: 0},
      container : '#gjs',
      fromElement: true,
      config: {
         undoManager: false
      },
      plugins: ['gjs-mjml'],
      pluginsOpts: {
        'gjs-mjml': {}
      }
    });
    window.editor = editor;
```

**Comment by artf** [comment]
there is no 'config' key

```js
editor = grapesjs.init({
      height: '100%',
      noticeOnUnload: 0,
      storageManager:{autoload: 0},
      container : '#gjs',
      fromElement: true,
      undoManager: false,
      plugins: ['gjs-mjml'],
      pluginsOpts: {
        'gjs-mjml': {}
      }
    });
    window.editor = editor;
```

**Comment by kavikaran** [comment]
i tried as you wrote in last reply . but it gave same error. So i tried 'config' key.
