### ISSUE TITLE
[0.1.5] Issue with plugin initialization

### ISSUE THREAD

**Issue by DRoet** [artf/grapesjs-mjml#110]
working codesandbox using the previous version (0.0.31):
https://codesandbox.io/s/jovial-jackson-gyyhf

broken version using the newest version (0.1.5):
https://codesandbox.io/s/stoic-water-2jfi5

you will see a stacktrace in the console
```js
grapesjs-mjml.min.js:2 Uncaught TypeError: Cannot read property 'innerHTML' of null
    at child.getTemplateFromEl (grapesjs-mjml.min.js:2)
    at child.getTemplateFromMjml (grapesjs-mjml.min.js:2)
    at child.render (grapesjs-mjml.min.js:2)
    at child.addToCollection (grapes.js? [sm]:36452)
    at eval (grapes.js? [sm]:36497)
```

**Comment by larsdecker** [comment]
mjml has changed its syntax with version 4.
Please update also your index.html to that, what we use in the current version of the plugin. Then the plugin should works fine.

**Comment by DRoet** [comment]
@larsdecker I've updated the second codesandbox using the code from the [demo](https://grapesjs.com/demo-mjml.html).
However this does not seem to solve the issue. I think it might be related to the esm-style import, which is quite common in frameworks like react/vuejs

**Comment by michibat01** [comment]
@DRoet @FlyveHest @larsdecker 
Seems that it doesn't work when the javascript file is generated with the webpack option:
`--env.production`

**Comment by larsdecker** [comment]
When we downgrade to mjml4-in-browser 1.1.1 then the problem is gone.
It seems related to the update of mjml 4.40.

**Comment by michibat01** [comment]
@larsdecker 
In the latest version of mjml-in-browser the [webpack.config.js](https://github.com/bures/mjml4-in-browser/commits/master/webpack.config.js) file has been changed.
I think the problem is in one of those commits

**Comment by larsdecker** [comment]
@bures
Can you look at it?  The problem only occurs when it is imported via esm-style import.

**Comment by bures** [comment]
I will check it. However, could someone make a minimalistic example project that doesn't work? I'm a bit tight with time. Thanks.

**Comment by ThomasChartron** [comment]
I also had to downgrade to version 0.0.31 to make it work, I had a TypeError different from the one posted but it looks like it comes from the same problem.
Would be great if someone could look into it to fix it into a new release and thanks for the work on mjml plugin !

**Comment by ThomasChartron** [comment]
I also had to downgrade to version 0.0.31 to make it work, I had a TypeError different from the one posted but it looks like it comes from the same problem.
Would be great if someone could look into it to fix it into a new release and thanks for the work on mjml plugin !

**Comment by ThomasChartron** [comment]
Thanks a lot for the work !
