### ISSUE TITLE
Highlight gone after moving component

### ISSUE THREAD

**Issue by kickbk** [artf/grapesjs-mjml#121]
On the demo site, click on a column component on the canvas. It will select it, highlight it with a blue border and show the component name on the top left hand corner. Great.
Now drag and drop it somewhere and try to click on the column again. It is then un-selectable. Clicking another column and back on the one we moved will work.
This is not a huge problem, but not a nice UX. Any idea why this is happening?

**Comment by artf** [comment]
This should be fixed in the latest release.
