### ISSUE TITLE
Style default value incorrect with right panel

### ISSUE THREAD

**Issue by CasperLaiTW** [artf/grapesjs-mjml#127]
Hi, I got some problem with component style default.

component had style default value, but all didn't show on right panel.

example:

<img width="1233" alt="螢幕快照 2019-09-11 下午3 10 43" src="https://user-images.githubusercontent.com/5094008/64675816-a2a6a280-d4a6-11e9-9be6-48ac99181a2a.png">

I think the image should have padding-bottom, but panel show all 0.

any way to get right value in panel?

**Comment by navewi** [comment]
I just noticed the same issue, every image or text has extra space but the padding values on the right are all set to 0. How can I get rid of that extra space? @artf 

For example: i want to use the image as an full-width hero image without any space to the left and right.
![image](https://user-images.githubusercontent.com/38751963/65967901-ac4a7700-e462-11e9-8c9d-26d10c3339fb.png)
In the Mmjl code there is no padding either:
![image](https://user-images.githubusercontent.com/38751963/65968017-dd2aac00-e462-11e9-8c64-ac47b7ff0c32.png)

**Comment by wheredidgogogo** [comment]
Hi guys,

This is an issue with us too - love the package!!  Would be willing to contribute some money to have this little bug fixed.

Cheers

Anthony

**Comment by Felix-Indoing** [comment]
Did you find a workaround for this problem?

**Comment by CasperLaiTW** [comment]
Hi guys,

there is related issues on https://github.com/artf/grapesjs/issues/2337

Follow the issue workaround, we have to change `style-default` to `style`

right panel will get correct values.

![style](https://user-images.githubusercontent.com/5094008/72121031-c61a2500-3394-11ea-9992-f6808accab7e.png)

@artf 

what's different between `style-default` and `style`?

**Comment by CasperLaiTW** [comment]
should we append `style-default` data into style on init?

https://github.com/artf/grapesjs-mjml/blob/master/src/components/index.js#L47

```
const style = { ...this.get('style-default'), ...this.get('style') };
```
