### ISSUE TITLE
How to define components for mailjet variables or a regex expression?

### ISSUE THREAD

**Issue by slellampati** [artf/grapesjs-mjml#128]
I am trying to create component for variable like {{ var:firstName:Joe }} using below code, 

```
const comps = editor.DomComponents;

    comps.addType('variable', {
      isComponent: (el: HTMLElement) => {
        if (el.innerHTML === '/({{ *|{%[^v^}]* )var:w{1,}[^}]*}{1,2}/igm') {
          log.debug('variable found: el:', el);
          return {
            type: 'variable'
          };
        }
      }
    });
```
It looked easy for creating component for html element but not able to find how to make it work for such regex expressions. I also tried using if(regex), if(el.tagName == regex) and if(el.innerText == regex) but nothing worked. 

I am trying to identify variables as component and display placeholder if default value available or the variable name using onRender() without effecting the final output which will be sent to server and then mailjet. 

I am liking grapesjs and it would be very useful if you can add support for this kind of variables by default like Text.

**Comment by artf** [comment]
```js
/your-regex/igm.test('Your string')
```

BTW, next time don't open issues related to JS (eg. ask them on StackOverflow)
