### ISSUE TITLE
Extending mj-section

### ISSUE THREAD

**Issue by LoFromCaumont** [artf/grapesjs-mjml#131]
I,
could you present an example of grapejs component extended from mj-section ?
It's just to include, at the right place (between others sections), a "short code" like this : 

<mj-section><mj-column>%myCode%</mj-column></mj-section>

**Comment by LoFromCaumont** [comment]
...like THIS : 
`<mj-section><mj-column>%myCode%</mj-column></mj-section>`

**Comment by artf** [comment]
Just create a [Block](https://grapesjs.com/docs/modules/Blocks.html) for your snippets
