### ISSUE TITLE
Missing mj-hero

### ISSUE THREAD

**Issue by codyng** [artf/grapesjs-mjml#133]
Hi there,

I am wondering if mj-hero component is missing in the current version.

Thanks a lot.

**Comment by NorthstarTech** [comment]
Hey @artf ,

I also want the mj-hero component for background images, as mj-section background images doesn't worked background-size attribute(cover and container) on large images. 

help Needed.
Thanks a lot

**Comment by DRoet** [comment]
https://github.com/artf/grapesjs-mjml/pull/142
