### ISSUE TITLE
Background-image isn't visible

### ISSUE THREAD

**Issue by navewi** [artf/grapesjs-mjml#139]
I added a background-image to a section in the editor and it isn't visible. 
This has worked before, it isn't working since this week. How can I fix this? 

This is on a local installation, but i also tried in the online demo and there's the same problem.
Thanks!

![image](https://user-images.githubusercontent.com/38751963/65968888-2d563e00-e464-11e9-96bc-6fe4e1c921b0.png)

It is also not in the mjml-code:
![image](https://user-images.githubusercontent.com/38751963/65969147-90e06b80-e464-11e9-94ba-2d4b9b4ab051.png)

**Comment by navewi** [comment]
Also another problem: 
Content is absolut messy after copying it:
Left one i made with drag an drop, right one is a copy from the first one.

![image](https://user-images.githubusercontent.com/38751963/65973329-6fcf4900-e46b-11e9-8e5f-a0cfa26b1c0d.png)

**Comment by DRoet** [comment]
Could you test if this is working again in `v0.1.15` + latest grapesjs?

**Comment by navewi** [comment]
Yeah i think it works again. Thanks @artf 
One thing ist still open: The Image and Spacer Block-Tags not closing properly. this causes that every element after them in the same section is missing after export and then import again.

**Comment by DRoet** [comment]
@navewi good find

**Comment by navewi** [comment]
@DRoet did you test this? I already had been testing what you want to merge before and it didn't work for me. Image and Spacer Problem is still there with the changes you made.

**Comment by DRoet** [comment]
@navewi hmm yeah there seems to be something else going on..

**Comment by DRoet** [comment]
ah gotcha, video helps a lot. thanks

**Comment by DRoet** [comment]
@artf it seems as if the `void` option is being ignored by the renderer:

```html
<mj-spacer/>
<mj-spacer/>
<mj-spacer/>
```

turns into:

```html
<td id="spacer">
    <td id="spacer">
        <td id="spacer">
        </td>
     </td>
</td>
```

instead of 

```html
<td id="spacer">
</td>
<td id="spacer">
</td>
<td id="spacer">
</td>
```

**Comment by artf** [comment]
@DRoet this is due to HTML5 which doesn't support custom void elements (GrapesJS uses the native HTML parser) so it tries to fix them somehow
