### ISSUE TITLE
Text box that does not appear !

### ISSUE THREAD

**Issue by FlashPapa** [artf/grapesjs-mjml#14]
When opens a document with this code
`<mj-container>
	<mj-section>
		<mj-column>
			<mj-text>Hello</mj-text>
		</mj-column>
	</mj-section>
	<mj-section>
		<mj-column>
			<mj-image src="http://test.png"/>
			<mj-text>simple text</mj-text>
		</mj-column>
	</mj-section>
</mj-container>
`

The text box does not open : `<mj-text>simple text</mj-text>` ???
But the code is good in the source !

**Comment by artf** [comment]
Discussed here #10 about the `<mj-image>` issue, to fix it, put the closing tag `<mj-image ...></mj-image>`

**Comment by FlashPapa** [comment]
This effectively corrects the problem !
Regards,

**Comment by FlashPapa** [comment]
I use ->

myString.replace(new RegExp("(<mj-image.*?>)", "gi"), "$1</mj-image>").replace(/\/>/g,'>');

Thanks !!!

**Comment by NorthstarTech** [comment]
@FlashPapa  is this issue resolved? I still get the issue of text not appearing when I have one column having mj-image and mj-text both.

**Comment by FlashPapa** [comment]
I have not tested since the last update

**Comment by NorthstarTech** [comment]
@FlashPapa Is it possible to test and verify it? Also let me know where u place this line statement in your code? myString.replace(new RegExp("(<mj-image.*?>)", "gi"), "$1").replace(//>/g,'>'); 
Help needed to resolve this issue.
Thanks

**Comment by FlashPapa** [comment]
So, yes =>
myString.replace(new RegExp("(<mj-image.*?>)", "gi"), "$1").replace(//>/g,'>'); 
Resolve the probleme but it is not very elegant ;)

**Comment by NorthstarTech** [comment]
ohh great!! in which file u place this line of code? @FlashPapa
