### ISSUE TITLE
uglify-js support

### ISSUE THREAD

**Issue by fusionbeam** [artf/grapesjs-mjml#143]
Hi,

I have noticed that since 0.1.x uglify-js is no longer supported. 
We have GrapesJS wrapped up in a vue.js project which relies on uglify-js (terser just doesn't work and breaks some dependencies).

Any thoughts on making grapesjs-mjml compatible with uglify? 
Uglify-js complains about the dynamic module requirements (using require with expressions rather than constants). 

Thank you,
R

**Comment by artf** [comment]
If you're talking about this
![Schermata 2020-02-04 alle 21 34 48](https://user-images.githubusercontent.com/11614725/73785807-53844580-4798-11ea-931e-e62fcc83d842.png)
this is from MJML library, not the plugin
