### ISSUE TITLE
Is CKEditor still compatible with the latest mjml-Editor-Version? 

### ISSUE THREAD

**Issue by navewi** [artf/grapesjs-mjml#145]
Hello, 
i tried to add the ckeditor to my local installation of grapesjs with mjml-plugin.
I get the error CKEditor is not defined. Is it still supposed to work? 

If I download the repository of the ckeditor directly from github (https://github.com/artf/grapesjs-plugin-ckeditor) and do the npm install etc. the editor plus cke works, but not in my already existing installation with mjml.

I added the grapesjs-plugin-ckeditor.min.js file and added the 'gjs-plugin-ckeditor' into plugin attribute the init function.

Thanks!

**Comment by kickbk** [comment]
@navewi I'm using the latest MJML 4.5.1 with the latest grapesjs-mjml and grapesjs and CKeditor works just fine.

**Comment by navewi** [comment]
@kickbk how exactly did you implement it?
if I do it like in the documentation i get that the ckeditor is not defined and if I include the cdn of ckeeditor this error is gone but it still does not work :(

**Comment by navewi** [comment]
Okay I think i just got it right. The cdn link was the wrong one i think
