### ISSUE TITLE
Export strips inline styles from button

### ISSUE THREAD

**Issue by kickbk** [artf/grapesjs-mjml#147]
Paste this MJML to import into the canvas:
```
<mj-body>
  <mj-section>
    <mj-column>
      <mj-button>
        <span style="color:#e74c3c;">Button</span>
      </mj-button>
    </mj-column>
  </mj-section>
</mj-body>
```
Great - it works. Now click the View Code button to export. You will notice that the span around the text that had the color style is gone and an id was entered instead.

This is a major problem as we use the export function to produce the MJML, and save MJML templates. Any solutions? Maybe a fix for the import/export?

**Comment by navewi** [comment]
I think because a span is an html element and the editor just handles it like a xml / mjml component. I think this is normal. 

You don't need the span, simply use code like this for the Button:  
`<mj-button color="#ea0000">Button</mj-button>`
Works great.

**Comment by kickbk** [comment]
Yes, you can change the color of the text of a button with the style manager. But we don't use the style manager to change the color of text because:

1. We use CKeditor, so when clients double click the text, I believe they expect the text to be editable (color included) with CKE and not the style manager. Also, allowing both CKE and the Style Manager to color text creates clashes and one or the other will stop working.

2. We cannot use the style manager to color buttons, but then use CKE to edit Text component color. Why use CKE to color Text component text you wonder? Because the Style Manager only applies color to ALL the text in a component, and as far as I can see, there is no way to select part of the text and color it separately.... Which is exactly why CKE wraps selected text with span tags.

Now regarding spans - Text components spans have no problem to export/import. So why does span in a button component gets converted? And how do we allow spans in the Button component?

Honestly, if there was a way to integrate the Style Manager color picker inside CKE, that would be so very cool. But I guess that's pretty much impossible or very complex. Regardless, the span issue will still exist, because what if one wanted they button to have part of the text in blue and the other in green.

**Comment by navewi** [comment]
@kickbk I think that spans in the mjml code are just not possible, but i don't have a solution for that, sorry.

But maybe you could help me with something. I also want to use the CKeditor but i have problem with it. Maybe you can tell me what you did to implement the ckeditor. (to avoid spamming this issue you can just open a issue on any of my repositories to help me if you can) thanks!

**Comment by DRoet** [comment]
I don't think this is something we can fix easily, I would recommend setting the styling on the button directly instead of using another span
