### ISSUE TITLE
mj-wrapper content is malformed

### ISSUE THREAD

**Issue by grant007** [artf/grapesjs-mjml#150]
To reproduce the problem...

1. import the following mjml into the editor

```html
<mjml>
  <mj-body>
    <mj-wrapper border="1px solid #000000" padding="50px 30px">
      <mj-section border-top="1px solid #aaaaaa" border-left="1px solid #aaaaaa" border-right="1px solid #aaaaaa" padding="20px">
        <mj-column>
          <mj-image padding="0" src="https://via.placeholder.com/150" />
        </mj-column>
      </mj-section>
      <mj-section border-left="1px solid #aaaaaa" border-right="1px solid #aaaaaa" padding="20px" border-bottom="1px solid #aaaaaa">
        <mj-column border="1px solid #dddddd">
          <mj-text padding="20px"> First line of text </mj-text>
          <mj-divider border-width="1px" border-style="dashed" border-color="lightgrey" padding="0 20px" />
          <mj-text padding="20px"> Second line of text </mj-text>
        </mj-column>
      </mj-section>
    </mj-wrapper>
  </mj-body>
</mjml>
```

2. Results in what appears to be an extra blank div before each content e.g. mj-image. See image below.
<img width="977" alt="Screen Shot 2019-11-01 at 8 46 33 AM" src="https://user-images.githubusercontent.com/814432/68026244-77118e80-fc85-11e9-86f8-40d7dd01b6af.png">

3. Brief examination of MJML plugin source code leads me to think the issue is something to do with the mj-section view's getChildSelector function in the case of nested within a mj-wrapper.

**Comment by artf** [comment]
Seems more like an issue with `getChildSelector` from mj-wrapper
