### ISSUE TITLE
[BUG] Columns have padding that is not really there

### ISSUE THREAD

**Issue by navewi** [artf/grapesjs-mjml#153]
Mj-Columns have a padding top and bottom that ist not really there:
![image](https://user-images.githubusercontent.com/38751963/68766781-d2e1fd00-061f-11ea-8db7-e3978c82fc7f.png)

In the exported html this space is not visible:
![image](https://user-images.githubusercontent.com/38751963/68766907-0cb30380-0620-11ea-9565-f8664ead51b7.png)

This is really bad when doing a new layout and the canvas in grapesjs is looking different than the generated html. How can I get rid of this extra space in the columns?

**Comment by Felix-Indoing** [comment]
Would like to hear an answer too.

**Comment by DRoet** [comment]
duplicate of https://github.com/artf/grapesjs-mjml/issues/167
