### ISSUE TITLE
How can i customize attibutes

### ISSUE THREAD

**Issue by JGalbois** [artf/grapesjs-mjml#154]
In the MJML, i have : 
` <mj-section background-color="#f0f0f0" id="i5ln" condition-test="Mytest" condition-operator="si">`

With custom attibutes: 
`condition-test` and `condition-operator`

But i see nothing in the HTML

How can i add new attibute ?

Thank's

**Comment by artf** [comment]
MJML doesn't pass custom attributes, you should extend the GrapesJS component in this case
