### ISSUE TITLE
I have forked the repo with several fixed applied found in the issue list

### ISSUE THREAD

**Issue by Felix-Indoing** [artf/grapesjs-mjml#156]
I am recently using this great plugin for generating MJML content. I read basically all the issue tickets / pull requests here and applied the proposed solutions to my fork. For anyone who is looking for a quick solution, please see here https://github.com/Felix-Indoing/grapesjs-mjml/commits/master

Please check all the fixes commits on Nov 23, 2019.

**Comment by larsdecker** [comment]
Can you please make a Pull Request, so that anyone can profit from fixed version.

**Comment by Felix-Indoing** [comment]
Sure here it is https://github.com/artf/grapesjs-mjml/pull/158

**Comment by DRoet** [comment]
PR was closed, some things got cherry picked
