### ISSUE TITLE
![cke](https://user-images.githubusercontent.com/31323376/52492895-0bc7df80-2b7f-11e9-8228-ebc3e8252a16.gif)

### ISSUE THREAD

**Issue by AliErdin** [artf/grapesjs-mjml#161]
![cke](https://user-images.githubusercontent.com/31323376/52492895-0bc7df80-2b7f-11e9-8228-ebc3e8252a16.gif)

Step1: select text and apply cke changes (bold, italic, whatever)
Step2: style element by changing color (or any other via StyelManager)
Step3: Select text and try t change something with cke

_Originally posted by @kickbk in https://github.com/artf/grapesjs-mjml/issues/68#issuecomment-461870029_

I faced the same error

**Comment by DRoet** [comment]
Could you test this in the latest v0.1.17 release? can't reproduce locally (note the demo is still using an older version)
