### ISSUE TITLE
Rendering differences

### ISSUE THREAD

**Issue by Jogai** [artf/grapesjs-mjml#167]
I see a major difference displaying MJML if I compare the 'official' editor with grapesjs. If I use the markup from my sample (kept it simple) https://mjml.io/try-it-live/HknhrPZmI in https://grapesjs.com/demo-mjml.html the difference is obvious (title bar too high, picture too small). This makes it a bit hard to provide a wysiwyg mail editor to the users. What can I do to improve this situation?

**Comment by DRoet** [comment]
This was done on purpose to make it easier to drag the columns, see: 
https://github.com/artf/grapesjs-mjml/blob/master/src/index.js#L64

This won't show up in the final HTML result
