### ISSUE TITLE
Custom mjml components

### ISSUE THREAD

**Issue by RyanFlm** [artf/grapesjs-mjml#169]
Is there a solution to add my own custom mjml components to the supported components of this plugin?

**Comment by HeyWrecker** [comment]
@RyanFlm Did you close this because you were able to figure it out on your own? If so, would you mind sharing? I'm attempting to create custom components as well and any insight you have to offer would be appreciated. Thanks!

Rick

**Comment by RyanFlm** [comment]
@HeyWrecker I'm not shure right now. I could have a look, on what I did, for you, if you want.

**Comment by HeyWrecker** [comment]
@RyanFlm Thanks, I appreciate that! But, turns out what I actually needed were custom blocks and those are a lot easier to deal with. :-)
