### ISSUE TITLE
Attributes being removed on load

### ISSUE THREAD

**Issue by DevonHansen** [artf/grapesjs-mjml#17]
I've noticed this issue on both my local installation and on the demo page you have set up.

When adding images from a different source (for example placeholders) the system removes all attributes from all mjml tags.

Investigations show that they are saving correctly, it is at load time. 

In the demo app I have set up a single image, changed the value of the src, then added a new item. This has caused the issue. I then removed the older image to show a smaller output. The designer shows a successful render, but below is what I see in gjs-mjml-components and gjs-mjml-html:

gjs-mjml-components:
`[
  {
    "tagName": "mj-container",
    "type": "mj-container",
    "removable": false,
    "draggable": false,
    "droppable": "[data-type=mj-section], [data-type=mj-wrapper]",
    "badgable": true,
    "stylable": [
      "width",
      "background-color"
    ],
    "highlightable": true,
    "copyable": false,
    "resizable": false,
    "editable": false,
    "layerable": true,
    "void": false,
    "state": "",
    "status": "",
    "content": "",
    "icon": "",
    "style": {
      "width": "600px"
    },
    "attributes": {
      "width": "600px"
    },
    "classes": [
      
    ],
    "script": "",
    "traits": [
      {
        "type": "text",
        "label": "",
        "name": "id",
        "min": "",
        "max": "",
        "value": "",
        "default": "",
        "placeholder": "eg. Text here",
        "changeProp": 0,
        "options": [
          
        ]
      },
      {
        "type": "text",
        "label": "",
        "name": "title",
        "min": "",
        "max": "",
        "value": "",
        "default": "",
        "placeholder": "eg. Text here",
        "changeProp": 0,
        "options": []
      }
    ],
    "custom-name": "Container",
    "components": [
      {
        "tagName": "mj-section",
        "type": "mj-section",
        "removable": true,
        "draggable": "[data-type=mj-container]",
        "droppable": "[data-type=mj-column]",
        "badgable": true,
        "stylable": [
          "vertical-align",
          "text-align",
          "padding",
          "padding-top",
          "padding-left",
          "padding-right",
          "padding-bottom",
          "background-color",
          "background-url",
          "background-repeat",
          "background-size",
          "border-radius",
          "border-top-left-radius",
          "border-top-right-radius",
          "border-bottom-left-radius",
          "border-bottom-right-radius",
          "border",
          "border-width",
          "border-style",
          "border-color"
        ],
        "highlightable": true,
        "copyable": true,
        "resizable": false,
        "editable": false,
        "layerable": true,
        "void": false,
        "state": "",
        "status": "",
        "content": "",
        "icon": "",
        "style": {
          "padding-top": "10px",
          "padding-bottom": "10px",
          "vertical-align": "top",
          "text-align": "center"
        },
        "attributes": {
          "padding-top": "10px",
          "padding-bottom": "10px",
          "vertical-align": "top",
          "text-align": "center"
        },
        "classes": [],
        "script": "",
        "traits": [
          {
            "type": "text",
            "label": "",
            "name": "id",
            "min": "",
            "max": "",
            "value": "",
            "default": "",
            "placeholder": "eg. Text here",
            "changeProp": 0,
            "options": []
          },
          {
            "type": "text",
            "label": "",
            "name": "title",
            "min": "",
            "max": "",
            "value": "",
            "default": "",
            "placeholder": "eg. Text here",
            "changeProp": 0,
            "options": []
          }
        ],
        "custom-name": "Section",
        "components": [
          {
            "tagName": "mj-column",
            "type": "mj-column",
            "removable": true,
            "draggable": "[data-type=mj-section]",
            "droppable": true,
            "badgable": true,
            "stylable": [
              "background-color",
              "vertical-align",
              "width",
              "border-radius",
              "border-top-left-radius",
              "border-top-right-radius",
              "border-bottom-left-radius",
              "border-bottom-right-radius",
              "border",
              "border-width",
              "border-style",
              "border-color"
            ],
            "highlightable": true,
            "copyable": true,
            "resizable": false,
            "editable": false,
            "layerable": true,
            "void": false,
            "state": "",
            "status": "",
            "content": "",
            "icon": "",
            "style": {
            },
            "attributes": {
            },
            "classes": [],
            "script": "",
            "traits": [
              {
                "type": "text",
                "label": "",
                "name": "id",
                "min": "",
                "max": "",
                "value": "",
                "default": "",
                "placeholder": "eg. Text here",
                "changeProp": 0,
                "options": [
                  
                ]
              },
              {
                "type": "text",
                "label": "",
                "name": "title",
                "min": "",
                "max": "",
                "value": "",
                "default": "",
                "placeholder": "eg. Text here",
                "changeProp": 0,
                "options": []
              }
            ],
            "custom-name": "Column",
            "components": [
              {
                "tagName": "mj-image",
                "type": "mj-image",
                "removable": true,
                "draggable": "[data-type=mj-column]",
                "droppable": 0,
                "badgable": true,
                "stylable": [
                  "width",
                  "height",
                  "padding",
                  "padding-top",
                  "padding-left",
                  "padding-right",
                  "padding-bottom",
                  "border-radius",
                  "border-top-left-radius",
                  "border-top-right-radius",
                  "border-bottom-left-radius",
                  "border-bottom-right-radius",
                  "border",
                  "border-width",
                  "border-style",
                  "border-color",
                  "container-background-color",
                  "align"
                ],
                "highlightable": false,
                "copyable": true,
                "resizable": false,
                "editable": false,
                "layerable": true,
                "void": true,
                "state": "",
                "status": "",
                "content": "",
                "icon": "",
                "style": {
                  "src": "http://placehold.it/350x250/78c5d6/fff",
                  "padding-top": "10px",
                  "padding-bottom": "10px",
                  "padding-right": "25px",
                  "padding-left": "25px",
                  "align": "center"
                },
                "attributes": {
                  "src": "http://placehold.it/350x250/78c5d6/fff",
                  "padding-top": "10px",
                  "padding-bottom": "10px",
                  "padding-right": "25px",
                  "padding-left": "25px",
                  "align": "center"
                },
                "classes": [
                  
                ],
                "script": "",
                "traits": [
                  {
                    "type": "text",
                    "label": "",
                    "name": "href",
                    "min": "",
                    "max": "",
                    "value": "",
                    "default": "",
                    "placeholder": "eg. https://google.com",
                    "changeProp": 0,
                    "options": [
                      
                    ]
                  },
                  {
                    "type": "text",
                    "label": "",
                    "name": "rel",
                    "min": "",
                    "max": "",
                    "value": "",
                    "default": "",
                    "placeholder": "",
                    "changeProp": 0,
                    "options": [
                      
                    ]
                  },
                  {
                    "type": "text",
                    "label": "",
                    "name": "alt",
                    "min": "",
                    "max": "",
                    "value": "",
                    "default": "",
                    "placeholder": "eg. Text here",
                    "changeProp": 0,
                    "options": [
                      
                    ]
                  },
                  {
                    "type": "text",
                    "label": "",
                    "name": "title",
                    "min": "",
                    "max": "",
                    "value": "",
                    "default": "",
                    "placeholder": "eg. Text here",
                    "changeProp": 0,
                    "options": [
                      
                    ]
                  }
                ],
                "src": "http://placehold.it/350x250/78c5d6/fff",
                "custom-name": "Image",
                "components": [
                  
                ]
              }
            ]
          }
        ]
      }
    ]
  }
]`

gjs-mjml-html:
`<mj-container><mj-section><mj-column><mj-image/></mj-column></mj-section></mj-container>`

**Comment by DevonHansen** [comment]
Found where the issue was. In components.js, line 62 you use getAttrToHTML(). I commented out the functionality of this it seems to have fixed it. 
It was getting all items, not just default style items, and deleting them. Because this is a work around rather than a fix I am not going to post a pull request.

**Comment by artf** [comment]
I don't get what exactly you've commented in getAttrToHTML

**Comment by DevonHansen** [comment]
Sorry, my mistake. This is the copy from the changes I've made:

```
getAttrToHTML() {
      let attr = Object.assign({}, this.get('attributes') || {});
      // let style = Object.assign({}, this.defaultStyle || {});
      // delete attr.style;
      // for (let prop in attr) {
      //   if (attr[prop] == style[prop]) {
      //     delete attr[prop];
      //   }
      // }
      return attr;
    },
```

**Comment by DevonHansen** [comment]
OK, to reproduce (seemed to work every time on this machine. Windows 10, Google Chrome, using the MJML Demo page - data cleared before starting these steps)

1) Drag and drop an image block above "My Awesome Text"
2) Double click image block to load asset manager
3) Double click any other image in the list
4) Check MJML code - At this point includes all attributes you'd expect
5) Refresh the page and check MJML code - All attributes are now removed and image changing src is not saved.

**Comment by artf** [comment]
Ok thanks, I was able to reproduce it

**Comment by artf** [comment]
Should be fixed in the lates release
