### ISSUE TITLE
MJML 3 Templates to MJML 4 latest

### ISSUE THREAD

**Issue by NorthstarTech** [artf/grapesjs-mjml#174]
@artf how can I migrate the mjml3 templates to mjml4. Please provide me the steps to do this process. Thanks alot.

**Comment by DRoet** [comment]
this is the wrong repository for your question, please checkout https://github.com/mjmlio/mjml

**Comment by NorthstarTech** [comment]
@DRoet I want to migrate the mjml3 templates to mjml4 using grapesjs-mjml. Is that possible?

**Comment by DRoet** [comment]
`grapesjs-mjml` >= `v0.1.15` works with mjml4, there is no included migration functionality so you will have to do it manually
