### ISSUE TITLE
MJML3 to MJML4

### ISSUE THREAD

**Issue by NorthstarTech** [artf/grapesjs-mjml#175]
How can I get the button of migrate in grapesjs mjml to migrate mjml3 to mjml4?? Help Needed. Link attached for reference.

https://user-images.githubusercontent.com/13240286/41559971-0eb83e2c-731c-11e8-9ce1-d9a6a0c9b2d6.gif

**Comment by DRoet** [comment]
this is the wrong repository for your question, please checkout https://github.com/mjmlio/mjml

**Comment by NorthstarTech** [comment]
@DRoet I want the button to migrate the mjml3 templates to mjml4 using grapesjs-mjml. Is that possible?

**Comment by DRoet** [comment]
buttons should still work in mjml4 but you have to manually migrate it urself
