### ISSUE TITLE
Defaults not being set in style manager when dropping blocks

### ISSUE THREAD

**Issue by rcloss** [artf/grapesjs-mjml#190]
When you drop a block like mj-image or mj-column there are default paddings that are applied but aren't reflected in the Style manager in the sidebar, this makes it confusing for a user who clicks on an image or a column and sees that the padding is 0 even though it's 10px (for example), it still works for editing, for now I'm updating things when you drop a block so that it displays properly but I have to go through every block and make check every setting to make sure the defaults are set which is irritating to manage

**Comment by DRoet** [comment]
Are you seeing this on the latest version (0.1.18)?

**Comment by rcloss** [comment]
Nope! Thanks that fixed it

**Comment by rcloss** [comment]
small update, mj-button is missing the padding-top default style for some reason

**Comment by DRoet** [comment]
Hmm I think thats by design, since the the default styling doesn't apply a top padding:

```js
'padding-bottom': '10px',
'padding-right': '25px',
'padding-left': '25px',
```

**Comment by rcloss** [comment]
Those might be the defaults but if you drop a button it has 10px of padding on top that can be changed, but it's showing 0px on the sidebar. So there's a disconnect somewhere

**Comment by DRoet** [comment]
You are right, mjml applies `padding: 10px 25px` to the buttons by default so we should reflect that on our end
