### ISSUE TITLE
Question: Is it possible to write an inline `grapes-mjml` custom component? (ie. no build system)

### ISSUE THREAD

**Issue by HeyWrecker** [artf/grapesjs-mjml#195]
Hello,

I'm working in an environment without a build system, so as a result I have to use the pre-built `grapesjs-mjml` plugin in my `grapesjs.init()`. I am trying to write a custom `grapejs-mjml` component as a function expression (ie. `const customComponentTypes = (editor) => {};` that can then be included via the `grapesjs.init()` `plugins` list.

However, I'm running into the obvious problems of not having access to the `coreMjmlModel` and `coreMjmlView` expressions along with other utilities such as `mjmlConvert` since those are part of the pre-built plugin script and I have no way of importing them separately for inline use.

Is there any way to gain a reference to the utilities and expressions required to create an inline `grapesjs-mjml` component? Or, am I going to have to find a way to incorporate a build system into my project, clone the full `grapesjs-mjml`, write the component as a stand-alone component js file, and run a build to get a complete minified file?

```javascript
const placeholderComponents = function(editor) {
    const type = 'spc-placeholder';
    editor.DomComponents.addType(type, {
        extend: 'text',
        extendFnView: ['onActive'],
        isComponent: function(el) {
            if (el.tagName === type.toUpperCase()) {
                return {
                    type: type,
                    content: el.innerHTML,
                    components: [],
                };
            }
        },
        model: {
            ...coreMjmlModel,
            defaults: {
                name: 'placeholder',
                draggable: '[data-gjs-type=mj-column], [data-gjs-type=mj-hero]',
                highlightable: false,
                stylable: [
                    'height', 'font-style', 'font-size', 'font-weight', 'font-family', 'color',
                    'line-height', 'letter-spacing', 'text-decoration', 'align', 'text-transform',
                    'padding', 'padding-top', 'padding-left', 'padding-right', 'padding-bottom',
                    'container-background-color'
                ],
                'style-default': {
                    'padding-top': '10px',
                    'padding-bottom': '10px',
                    'padding-right': '25px',
                    'padding-left': '25px',
                    'font-size': '13px',
                    'line-height': '22px',
                    'align': 'left',
                },
            },
        },
        view: {
            ...coreMjmlView,
            tagName: 'tr',
            attributes: {
            style: 'pointer-events: all; display: table; width: 100%',
        },
        getMjmlTemplate: function() {
            return {
                start: `<mjml><mj-body><mj-column>`,
                end: `</mj-column></mj-body></mjml>`,
            };
        },
        getTemplateFromEl: function(sandboxEl) {
            return sandboxEl.querySelector('tr').innerHTML;
        },
        getChildrenSelector: function() {
            return 'td > div';
        },
        /**
        * Prevent content repeating
        */
        renderChildren: function() {
            coreMjmlView.renderChildren.call(this);
        },
        /**
        * Need to make text selectable.
        */
        onActive: function() {
            this.getChildrenContainer().style.pointerEvents = 'all';
        },
     },
    });
};
```

**Comment by DRoet** [comment]
Are you looking to add a new mjml-component or do you just want to create a custom block that you can drag and drop into your editor?

To add a custom block you can add it to the `BlockManager` like so:

```js
editor.BlockManager.add('custom-block', {
   category: 'section',
   label: '3/7 split',
   attributes: {
      title: '3/7 split',
      class: 'gjs-fonts gjs-f-b37'
   },
   class: 'gjs-fonts gjs-f-b37',
   content: `<mj-section background-color="#FFFFFF">
                <mj-column width="30%" border-radius="0 0 0 0" padding="10px">
                   <mj-text font-family="Roboto, Helvetica, sans-serif" font-size="17px" line-height="24px" color="#616161" align="center">
                      default text
                   </mj-text>
                </mj-column>
                <mj-column width="70%" border-radius="0 0 0 0" padding="10px">
                   <mj-text font-family="Roboto, Helvetica, sans-serif" font-size="17px" line-height="24px" color="#616161" align="center">
                      default text
                   </mj-text>
                </mj-column>
             </mj-section>`
})
```

If you want to add a new mjml component (for example `mj-carousel`) feel free to submit a PR and I can take a look to merge it in.

**Comment by HeyWrecker** [comment]
@DRoet actually, I think a custom block would work just fine. My use case is adding static custom placeholders (ex. `[: email :]` that would then get parsed server-side. So if I can do that as a block with a little mjml wrapping it, that should do nicely. That looks like what you're suggesting via the example.

**Comment by DRoet** [comment]
Ok feel free to close this issue if it's resolved by using custom blocks

**Comment by HeyWrecker** [comment]
I will. Thanks @DRoet Daan. Just a real quick question- how do I make the block read only?

**Comment by DRoet** [comment]
Could you try using the `disable` property and using grapesjs > `0.16.12` ?

**Comment by HeyWrecker** [comment]
I will look into it, thanks for the pointer!

**Comment by HeyWrecker** [comment]
@DRoet Hi Daan. I am using GrapesJS `0.16.18` and have tried configuring the block as follows:

```javascript
block_manager.add('{{ data.block_name }}', {
    category: '{{ placeholder.category }}',
    label: '{{ data.label }}',
    content: '<mj-text>{{ data.tag }}</mj-text>',
    attributes: {
        class: 'gjs-fonts gjs-f-text',
        title: '{{ data.tooltip }}',
        disable: true
    },
});
```

But the block continues to be editable (ie. I can double-click on it in the canvas and change the content). I am configuring the block incorrectly? I did not see any documentation regarding making blocks read only in the GrapesJS docs or GrapesJS MJML Git site.

**Comment by DRoet** [comment]
Hmm `disable` might not be the thing you are looking for, you could try and override some of the grapesjs-properties using `data-gjs-{property name}` on the block like this:

```js
block_manager.add('appointment-location-email', {
    category: 'Appointment Placeholders',
    label: 'Location - Email',
    content: '<mj-text data-gjs-draggable="false" data-gjs-droppable="false" data-gjs-editable="false" data-gjs-hoverable="false" data-gjs-selectable="false" data-gjs-propagate="['draggable', 'droppable', 'editable', 'hoverable', 'selectable']">[:appointment_location_email:]</mj-text>',
    attributes: {
        class: 'gjs-fonts gjs-f-text',
        title: 'Drag to insert the appointment location email address placeholder.',
        disable: true
    },
 });
```

You can read more on the properties [here](https://grapesjs.com/docs/api/component.html#properties)

**Comment by HeyWrecker** [comment]
@DRoet Daan, that did it. Thank for the help! It was very much appreciated!

**Comment by RakulAgn** [comment]
> Are you looking to add a new mjml-component or do you just want to create a custom block that you can drag and drop into your editor?
> 
> To add a custom block you can add it to the `BlockManager` like so:
> 
> ```js
> editor.BlockManager.add('custom-block', {
>    category: 'section',
>    label: '3/7 split',
>    attributes: {
>       title: '3/7 split',
>       class: 'gjs-fonts gjs-f-b37'
>    },
>    class: 'gjs-fonts gjs-f-b37',
>    content: `<mj-section background-color="#FFFFFF">
>                 <mj-column width="30%" border-radius="0 0 0 0" padding="10px">
>                    <mj-text font-family="Roboto, Helvetica, sans-serif" font-size="17px" line-height="24px" color="#616161" align="center">
>                       default text
>                    </mj-text>
>                 </mj-column>
>                 <mj-column width="70%" border-radius="0 0 0 0" padding="10px">
>                    <mj-text font-family="Roboto, Helvetica, sans-serif" font-size="17px" line-height="24px" color="#616161" align="center">
>                       default text
>                    </mj-text>
>                 </mj-column>
>              </mj-section>`
> })
> ```
> 
> If you want to add a new mjml component (for example `mj-carousel`) feel free to submit a PR and I can take a look to merge it in.



> Are you looking to add a new mjml-component or do you just want to create a custom block that you can drag and drop into your editor?
> 
> To add a custom block you can add it to the `BlockManager` like so:
> 
> ```js
> editor.BlockManager.add('custom-block', {
>    category: 'section',
>    label: '3/7 split',
>    attributes: {
>       title: '3/7 split',
>       class: 'gjs-fonts gjs-f-b37'
>    },
>    class: 'gjs-fonts gjs-f-b37',
>    content: `<mj-section background-color="#FFFFFF">
>                 <mj-column width="30%" border-radius="0 0 0 0" padding="10px">
>                    <mj-text font-family="Roboto, Helvetica, sans-serif" font-size="17px" line-height="24px" color="#616161" align="center">
>                       default text
>                    </mj-text>
>                 </mj-column>
>                 <mj-column width="70%" border-radius="0 0 0 0" padding="10px">
>                    <mj-text font-family="Roboto, Helvetica, sans-serif" font-size="17px" line-height="24px" color="#616161" align="center">
>                       default text
>                    </mj-text>
>                 </mj-column>
>              </mj-section>`
> })
> ```
> 
> If you want to add a new mjml component (for example `mj-carousel`) feel free to submit a PR and I can take a look to merge it in.

hey @DRoet I am looking for creating something like this 
<mj-coupon></mj-coupon>

A MJML CUSTOM COMPONENT and i need all mj-text stylables to mj-coupon and also i have doubt i need to create this tag through mjml after that i need to use the tag in grapesjs mjml but by default in grapesjs mjml in supported tag there is no option to support for custom tags
