### ISSUE TITLE
Social custom selection not changing social element behavior

### ISSUE THREAD

**Issue by premhunt** [artf/grapesjs-mjml#196]
When we change social icon from settings and select custom. It is not changing the default selected type.
Step-1: Drag social element 
Step-2: Check the code 
![image](https://user-images.githubusercontent.com/3192603/90717097-55dd6580-e2cc-11ea-828a-25c8a802e47a.png)
Step-3: Go to settings and change to custom
![image](https://user-images.githubusercontent.com/3192603/90717150-858c6d80-e2cc-11ea-9c7b-ff058f56605b.png)
Step-4: Go back to code mode and check for change, we still see facebook, it should change to custom
![image](https://user-images.githubusercontent.com/3192603/90717251-c97f7280-e2cc-11ea-9841-ac6c59e6f7bc.png)

**Comment by premhunt** [comment]
Seems I have found the reason , please let me know, if it is fine
Line number - 34 in file SocialElement.js need to change from {  value: '', name: 'Custom' }, to { value: 'custom', name: 'Custom' },

**Comment by DRoet** [comment]
uhmm yeah usually custom social elements shouldn't have a `name` property at all, but having `name="custom"` is probably fine

**Comment by DRoet** [comment]
released in `v0.2.5`

**Comment by premhunt** [comment]
Thanks @DRoet
