### ISSUE TITLE
Library in dist folder not up to date

### ISSUE THREAD

**Issue by SolutionsSwift** [artf/grapesjs-mjml#20]
Hi,

I discovered that in your demo, the latest version is used of grapes-mjml.min.js.
The version in the demo is:  0.0.24.
The dist folder is still not updated with this version and its stuck on 0.0.12.
I have no issues when using the latest version, the only problem is that i don't get it minified :/

Could you please update the dist folder with the latest minified version of grapes-mjml.in.js?

Kind regards,

Stephan Hovius

**Comment by StephanHovius** [comment]
I also found out that version 0.0.24 give some error about unescaped backslashes. 
for example --> row 38144: "Backslash": "\",
this should be "Backslash": "\\",

also setminus, setmn, smallsetminus have this problem.

**Comment by artf** [comment]
@StephanHovius this plugin comes with MJML library inside and what you mention is from their code. I've also disabled the minification as it was failing with the mjml code. Unfortunately, I didn't have much time to investigate it

**Comment by DRoet** [comment]
should be fixed and we provide minification nowadays
