### ISSUE TITLE
mj-image size limited to 550px

### ISSUE THREAD

**Issue by ditschedev** [artf/grapesjs-mjml#202]
Hey there,

**Edit**
Maybe this is a reference to #151 or #71 as they sounded similar.

I wanted to widen the mj-body to our desired desktop size of `820px`. After doing so everything adjusted just fine, but not the images. After inspecting their table-structured HTML markup I saw, that the parent `td` element has a fixed with of `550px`. Which is odd as I can't find any reference to this in the code. Is this a default setting of MJML or am I missing something?

Here is the rendered HTML of the editor:

```html
<tr data-gjs-type="mj-image" draggable="true" data-highlightable="1" src="https://dynamail.jkq.local/assets/03f9df38-208f-4465-99ed-d936cc32aabe" padding="10px 25px 10px 25px" id="i4zmh" width="865px" en="" style="pointer-events: all; display: table; width: 100%; user-select: none;" class="gjs-selected" height="81.1333px" align="center">
    <td style="font-size: 0px; padding: 10px 25px; word-break: break-word; pointer-events: none;" align="center">    
      <table role="presentation" style="border-collapse: collapse; border-spacing: 0px; pointer-events: none;" cellspacing="0" cellpadding="0" border="0">
        <tbody style="pointer-events: none;">
          <tr style="pointer-events: none;">
            <td style="width: 550px; pointer-events: none;">
                <img src="https://dynamail.jkq.local/assets/03f9df38-208f-4465-99ed-d936cc32aabe" style="border: 0px none; display: block; outline: currentcolor none medium; text-decoration: none; height: 81.1333px; width: 100%; font-size: 13px; pointer-events: none;" width="550" height="81">
            </td>
          </tr>
        </tbody>
      </table>
    </td>
</tr>
```

Cheers
Toby

**Comment by DRoet** [comment]
Do you see a difference of behavior if you drop the mjml code into https://mjml.io/try-it-live ?

**Comment by ditschedev** [comment]
Dropping the MJML code into the live editor at mjml.io the image acts as expected spanning the whole width.
The parent `td` of the image gets a fixed with of `770px` which is fine.

**Comment by DRoet** [comment]
could you provide a minimal reproduction (mjml-code) of what you are using?

**Comment by ditschedev** [comment]
Funny enough, the problem only occurs in the grapesjs editor. Once I generate the HTML, I get the correct values and the images are spanning the full width.

Here is a stripped down version of my mjml code.

```
<mjml>
  <mj-body width="820px">
    <mj-section>
      <mj-column>
        <mj-text font-size="9px" color="#000000">{TRACKER_IMAGE}</mj-text>
      </mj-column>
    </mj-section>
    <mj-section>
      <mj-column>
        <mj-text>Insert text here</mj-text>
      </mj-column>
    </mj-section>
    <mj-section>
      <mj-column>
        <mj-image src="https://via.placeholder.com/920x90?text=Should be full width"></mj-image>
      </mj-column>
    </mj-section>
  </mj-body>
</mjml>
```

**Comment by ditschedev** [comment]
@DRoet Don't want to get on anyones nerves, but I need the images to be sized correctly in the editor as they are displayed in the final email, as our clients are not that technically affine. 

Any progress or a guess, where this problem is coming from? Thanks in advance!

**Comment by DRoet** [comment]
Could you try this in https://github.com/artf/grapesjs-mjml/releases/tag/v0.2.9

I'm not sure if my patch is optimal, but it seems to do the job

**Comment by ditschedev** [comment]
That seems to to the job, I'am closing this for now.
Thanks!
