### ISSUE TITLE
Is this not compatible with the latest grapesjs?

### ISSUE THREAD

**Issue by ekr3peeK** [artf/grapesjs-mjml#213]
When trying to use this with grapesjs version `0.16.27`, I am getting the following errors in the console, whenever I select an element:

```
Uncaught TypeError: t.getSelectorsString is not a function
```

I am currently using the `0.3.2` version of the plugin from npm. Aren't these two versions compatible?

**Comment by ekr3peeK** [comment]
I've downgraded my grapesjs to the minimum required version, `0.15.9` and the error disappeared. So this is definitely not working with the latest grapesjs.

**Comment by ekr3peeK** [comment]
Okay, my mistake, it seems to work now, that means I've messed up something...

**Comment by gaarlos** [comment]
Hi @ekr3peeK , how did you solved it? I'm getting the same error 😕

**Comment by ekr3peeK** [comment]
@gaarlos I think it was caused by some outdated dependency. Because, I tried downgrading both plugins to a smaller version number, it started working then, then I upgraded them to the latest one again, and it works also, without the errors. Maybe try downgrading both plugins with one major version, and then upgrade them again to their latest versions.

**Comment by gaarlos** [comment]
@ekr3peeK it worked! Thank you! 🥳
