### ISSUE TITLE
HTML Script Src

### ISSUE THREAD

**Issue by dreamsight** [artf/grapesjs-mjml#214]
Hi
Just downloaded the most recent version of this package where I found the index html page has some paths that need correcting, one of them is <script src="//unpkg.com/grapesjs@0.10.7/dist/grapes.min.js"></script> and should be:

<script src="https://unpkg.com/grapesjs@0.10.7/dist/grapes.min.js"></script> the server does not redirect from http

also some of the paths point to folders that do not exist, I have corrected these for my own tests but it may be a good idea for other users?

There is no JS folder in package.
There is no Private folder and could not find ajaxable.min.js

Thanks.

**Comment by DRoet** [comment]
which index.html are you referencing exactly?

**Comment by dreamsight** [comment]
Hello
The one that comes with the package.
![image](https://user-images.githubusercontent.com/36543801/99965884-6bf83780-2d8d-11eb-8908-c6a4b1c404a4.png)

**Comment by DRoet** [comment]
yeah I'm still not sure where you are getting this from.

this repo has:
https://github.com/artf/grapesjs-mjml/blob/master/index.html

**Comment by dreamsight** [comment]
Hello Apologies I followed a link on the web page builder page https://github.com/artf/grapesjs Here:

![image](https://user-images.githubusercontent.com/36543801/100201292-ca412980-2ef7-11eb-8185-65eab5f74c62.png)

which led me to:

https://github.com/artf/grapesjs-preset-newsletter

An older version, should have looked harder I thought the project had not been updated in a while :)

Thanks

**Comment by DRoet** [comment]
I personally don't maintain that repository so there is not much I can do.
