### ISSUE TITLE
Docker image?

### ISSUE THREAD

**Issue by loganto** [artf/grapesjs-mjml#216]
is there a grapesjs docker image anywhere?   
   
Im looking for some selfhosted email builder I can just spin up on my network box and use for testing/building/editing email templates.

**Comment by DRoet** [comment]
Nope, this is a bit out of scope for the project and something you'll have to build on your own.

**Comment by gustavocs97** [comment]
here it goes, but still need figure it out how use still on base withou nothing, have no blocks like.

https://github.com/gustavocs97/GrapesJS-dockerized
