### ISSUE TITLE
Toolbar copy not working properly for column.

### ISSUE THREAD

**Issue by skbhagat40** [artf/grapesjs-mjml#221]
On selecting a column, clicking copy on it - 

1.  Does nothing for single column (on first click).
2. Increases the padding for 2 columns (on first click).

On 2nd click onwards, it creates the copy of column

**Comment by dervagabund** [comment]
I can confirm this - on colum copy and also when dropping a new column in the parent container - happens. this looks like a refresh issue. if you drag and drop the column container (even on the same place) it refreshes correctly.

**Comment by artf** [comment]
This should be fixed in the latest release.
