### ISSUE TITLE
Question: MJ-Hero - How do you change background image?

### ISSUE THREAD

**Issue by HeyWrecker** [artf/grapesjs-mjml#226]
We recently upgraded our version of the plug-in to the latest available and see that the `mj-hero` and `mj-wrapper` are implemented.

Unless I'm missing something, it doesn't appear that I can change the background image. When I click on the component and select the attributes/properties section, there is no field for background image or for opening any kind of image browser to update it. Any help would be appreciated!

Thanks,
Rick Zawadzki

**Comment by mingxin-yang** [comment]
Hi, do you have a solution about this @HeyWrecker
