### ISSUE TITLE
Where's the source code of the demo?

### ISSUE THREAD

**Issue by KevinShea1990** [artf/grapesjs-mjml#227]
The demo project ( https://grapesjs.com/demo-mjml.html )  provides some useful information on how to use the grapesjs-mjml. However, I cannot find source code of the demo project.  Where can I find it?

Especially, the demo project has custom ckeditor. I don't know how to integreate ckeditor in my project. It'd be very helpful to find an example of it.

**Comment by DRoet** [comment]
I don't think the demo page is open source, it also might need a upgrade since it is running a pretty old version of grapesjs-mjml and grapesjs. I would recommend cloning this repro and running the dev server to test things out for now

**Comment by udayapitchika** [comment]
@DRoet I think the demo pages are open source. All the demo pages are in gh-pages branch in grapesjs repo.
@KevinShea1990 Here's the source code for the demo you are looking for
https://github.com/artf/grapesjs/blob/gh-pages/demo-mjml.html
