### ISSUE TITLE
dragging additional social element not working

### ISSUE THREAD

**Issue by rcloss** [artf/grapesjs-mjml#242]
I've confirmed this is happening in the demo also, but if you add a Social Group block the first time you add a social element it doesn't display, but as soon as you drag elements around it appears and it also appears if you save the template and come back.

If you add a second one it displays just fine, not sure what the issue is

**Comment by rcloss** [comment]
It appears the same issue is happening with NavBar and NavBarLink

**Comment by slipperyfrank** [comment]
I've noticed the same behaviour when duplicating columns, navbar links, social elements.

**Comment by slipperyfrank** [comment]
Duplicate of #182

**Comment by artf** [comment]
Closing this one as it should be already fixed
