### ISSUE TITLE
mj-image source no longer works on https site

### ISSUE THREAD

**Issue by IceCrystal0k** [artf/grapesjs-mjml#243]
How to reproduce

open demo site: https://grapesjs.com/demo-mjml.html
drag an image
The image doesn't appear.
In browser console the following error appears: Failed to load resource: net::ERR_CERT_DATE_INVALID

If you open the image link in a new tab and replace http with https, the browser shows an error: Your connection is not private

Either update the source in blocks.js, from: 'http://placehold.it/'  to 'https://via.placeholder.com/' (the rest of the parameters remain the same) or provide a way to specify the source of the image by parameters.

I think same issue happens also for grapesjs-preset-newsletter

This can be used as an workaround: 
[#188](https://github.com/artf/grapesjs-mjml/issues/188)

**Comment by DRoet** [comment]
Contributions are always welcome

**Comment by IceCrystal0k** [comment]
Forked it here:
