### ISSUE TITLE
BUG: When setting bg color on mj-wrapper the content disappears

### ISSUE THREAD

**Issue by josfh2005** [artf/grapesjs-mjml#245]
**Version:**
grapes: 0.16.34
grapes-mjml: 0.5.2

**Are you able to reproduce the bug from the demo?**

 - [X] Yes
 - [ ] No

**What is the expected behavior?**

The canvas show the content and the bg color in the mj-wrapper.

*Describe the bug **detailed***

The bug occurs after I add a new mj-section inside the mj-wrapper.
Then when I change the background color, the mj-wrapper disappears from the canvas, the model is fine, it just seems to view related to the view.

**What is the current behavior?**

The mj-wrapper disappears from the canvas.

**Are you able to attach screenshots, screencasts or a live demo?**

 - [X] Yes (attach)
 - [ ] No

Setup to test:
https://jsfiddle.net/8jaf1vtp/7/

Video to reproduce the bug:
https://recordit.co/h6jcU5IeAe

**Comment by artf** [comment]
Closing this one as it should be already fixed.
