### ISSUE TITLE
Multi-columns issue on Chrome

### ISSUE THREAD

**Issue by Bran72** [artf/grapesjs-mjml#259]
Hi @artf ,

I'm facing an issue between Firefox and Chrome when using a multi-columns (2, 3,...).
In Firefox it's well rendered when I load my template, not in Chrome. But if I drag again a column block, everything re-render well.
Did u have any idea ? :/ 
Thanks !

Firefox: 
![firefox](https://user-images.githubusercontent.com/36424448/136401100-ac0d3a18-fe43-4b5f-8439-bcacdca7e263.png)

Chrome: 
![chrome](https://user-images.githubusercontent.com/36424448/136401141-08279b35-f689-473a-903f-e6b5765e28d5.png)

My config object:
![code](https://user-images.githubusercontent.com/36424448/136401424-ea84b1a2-4e12-43a6-b777-56341bca3006.png)

**Comment by Bran72** [comment]
Up ?

**Comment by artf** [comment]
Closing this one as it should be already fixed.
