### ISSUE TITLE
Give a name to the main block manager ?

### ISSUE THREAD

**Issue by TomAtTeam** [artf/grapesjs-mjml#266]
Hi, 

I would like to add a name to the block manager on the right so I can organize better my builder. 

![Capture d’écran (226)](https://user-images.githubusercontent.com/94383921/141813273-0229210f-3f70-4099-83cf-a7899c986111.png)

In this case I would like to give the name "Basic" to the block manager like this : 

![Capture d’écran (227)](https://user-images.githubusercontent.com/94383921/141813654-750b44eb-89c0-4abb-bf51-1d4242219ce5.png)

How can I proceed ? 

Thank you. 

Thomas

**Comment by thewrath** [comment]
Hi,

You can use the block manager from the editor to get a specific block and set it's category.

Here it's a snippet on how i use it :

```js
const categoryBlocks = { "Positionning": [ "mj-1-column", "mj-2-columns", "mj-3-columns", "mj-divider", "mj-spacer", "mj-divider", "mj-navbar", "mj-navbar-link", "mj-hero", "mj-wrapper", ], "Content": [ "mj-image", "mj-text", "mj-button", "mj-social-group", "mj-social-element", "mj-raw", ] } for (const [key, value] of Object.entries(categoryBlocks)) { value.forEach(b => { const block = editor.BlockManager.get(b); if (block) { block.set('category', {label: key, open: false}) } }) } 
```

**Comment by TomAtTeam** [comment]
Hi, 

Thank you very much for your answer, that's exactly what I was looking for and it works perfectly !

Have a nice day !

Thomas
