### ISSUE TITLE
mjml css issue

### ISSUE THREAD

**Issue by Kav-i** [artf/grapesjs-mjml#27]
i got below mjml theme using editor.getHtml().

but when i display to my project. it converts in html and send it as an email.

i have attached image.

```
<mjml>
<mj-body>
<mj-container min-height="100px">
<mj-section>
<mj-column>
<mj-text>Content 1</mj-text>
</mj-column>
<mj-column>
<mj-text>Content 2</mj-text>
</mj-column>
<mj-column>
<mj-text>Content 3</mj-text>
</mj-column>
</mj-section>
</mj-container>
</mjml>
</mj-body>
```
![screenshot from 2017-11-10 18-36-06](https://user-images.githubusercontent.com/33346887/32659760-3c9067c6-c646-11e7-90e2-b8c7befd9d00.png)

**Comment by artf** [comment]
`editor.getHtml()` will actually return the MJML in this case, you can get the final HTML by using `editor.runCommand('mjml-get-code').html`
