### ISSUE TITLE
[bug] Moving one column inside a three columns component

### ISSUE THREAD

**Issue by gustavohleal** [artf/grapesjs-mjml#281]
This bug is reproducible in the demo.

Once you drag a three column component to the canvas, try to move one of the columns to the side (changing the order of them).
The column moved gets lost. But if you move another column to the side, the missing column comes back and the recently moved gets out of the canvas. As you can see in the video below, the column is lost from the canvas but still remains on the code exporter.
And if you hit F5 to reload the page all the three columns comes back in the order you moved them.

https://user-images.githubusercontent.com/22385451/159769437-e4b67472-8cc5-4222-a652-6891d3ba494d.mp4

I didn't find any other issues related to this.

**Comment by ronaldohoch** [comment]
Super Up!

**Comment by gustavohleal** [comment]
The same bug happens with the NavBar component when you move one of the navbar links. I believe it have to do with the way the width of each element is calculate.

**Comment by artf** [comment]
This should be fixed in the latest release.
