### ISSUE TITLE
Layer Manager don't hide mjml elements.

### ISSUE THREAD

**Issue by ronaldohoch** [artf/grapesjs-mjml#288]
When we goes to layer manager and hide some components, the same isn't removed from canva. 
Check the steps:

1- Open the mjml demo.
![image](https://user-images.githubusercontent.com/2287371/166559327-2a14e346-e74b-4088-9183-9b34acbd670e.png)

2- Go to layer manager a open until find a text
![image](https://user-images.githubusercontent.com/2287371/166561660-357f4443-da5e-4e7b-8346-d86122235a9f.png)

3- Click on the eye and see the elements don't hidding.

**Comment by artf** [comment]
This should be fixed in the latest release.
