### ISSUE TITLE
mjml responsive issue

### ISSUE THREAD

**Issue by NorthstarTech** [artf/grapesjs-mjml#29]
This code is not responsive on mobile. Text is viewing on left corner and image is in center. but in designing template, it is viewing fine. How should I fix this? Also, on outlook, it looks totally different, not working properly.

<mjml>
  <mj-body>
    <mj-container background-color="rgba(23,102,234,0.91)">
      <mj-section>
        <mj-column>
          <mj-text>Insert text here
          </mj-text>
          <mj-image src="http://placehold.it/350x250/78c5d6/fff"/>
        </mj-column>
        <mj-column>
          <mj-text>Insert text here
          </mj-text>
          <mj-image src="http://placehold.it/350x250/78c5d6/fff"/>
        </mj-column>
      </mj-section>
    </mj-container>
  </mj-body>
</mjml>

**Comment by artf** [comment]
Seems more like [mjml](https://github.com/mjmlio/mjml)'s issue not of the plugin
