### ISSUE TITLE
editor.runCommand('mjml-get-code'); undefined result

### ISSUE THREAD

**Issue by graphixx** [artf/grapesjs-mjml#299]
I try to get de HTML full inline code and in use of:
editor.runCommand('mjml-get-code');
I get a "undefined" response.

In the same way the use of:
var Css = editor.getCss();
var Html = editor.getHtml();
var cmdGetCode = Css + Html;
contentEl.value = cmdGetCode;
I get the MJML code instead the FULL HTML code.

Please what is the correct way to GET the FULL HTML code,
please, BEST REGARDS.

**Comment by artf** [comment]
Use this command `editor.runCommand('mjml-code-to-html')`

**Comment by graphixx** [comment]
Soo perfect I use:
var Email = editor.runCommand('mjml-code-to-html').html;
Thanks for the guide bro, best regards.
