### ISSUE TITLE
Error Start on Windows

### ISSUE THREAD

**Issue by rcorzogutierrez** [artf/grapesjs-mjml#3]
On windows 10 show this error
![image](https://user-images.githubusercontent.com/5765375/28075344-39ffefcc-6629-11e7-8160-454fada35e70.png)

**Comment by artf** [comment]
thanks @rcorzogutierrez at the moment I'm not using any cross env helper, for now update package.json manually like this:
```js
"scripts": {
    "...": "SET WEBPACK_ENV=....",
  }
```

**Comment by DRoet** [comment]
should be fixed nowadays
