### ISSUE TITLE
ckeditor creates spans inside `mj-text`

### ISSUE THREAD

**Issue by Geczy** [artf/grapesjs-mjml#36]
I think this is undesired behavior. Believe it should rather apply the styles to `mj-text` element

```html
<mjml>
  <mj-body>
    <mj-container>
      <mj-section>
        <mj-column>
          <mj-text>
            <span style="color:#000000;">Start from here</span>
          </mj-text>
        </mj-column>
      </mj-section>
    </mj-container>
  </mj-body>
</mjml>
```

**Comment by artf** [comment]
>  `MjText` can contain any HTML tag with any attributes ([source](https://mjml.io/documentation/#mjml-text))

Well referring to MJML's documentation using spans inside `mj-text` shouldn't be an issue, also because I do not see how else you could format the inner text
