### ISSUE TITLE
Can't add 3rd column more than once

### ISSUE THREAD

**Issue by Geczy** [artf/grapesjs-mjml#37]
Weird inconsistencies

http://grapesjs.com/demo-mjml.html

Try dragging `column 3` twice or 3 times into the template

**Comment by artf** [comment]
Can't reproduce it Matt, might this be your case https://github.com/artf/grapesjs/issues/595 ?

**Comment by Geczy** [comment]
Yeah looks the same. All I do is drag x amount of times and it stops working

**Comment by DRoet** [comment]
I can't reproduce this anymore, even in the demo. closing this for now
