### ISSUE TITLE
ALL mjml styles are stripped - demo included

### ISSUE THREAD

**Issue by Geczy** [artf/grapesjs-mjml#38]
http://grapesjs.com/demo-mjml.html

1. Add a text block or a column block to change the template
2. Refresh the page
3. View export html

This is a big issue

# Before
![image](https://user-images.githubusercontent.com/1036968/33150700-a93722c4-cfa2-11e7-9df4-40f65e92c0fc.png)

# After
![image](https://user-images.githubusercontent.com/1036968/33150680-92652668-cfa2-11e7-82d1-311cd12b0c0f.png)

**Comment by DevonHansen** [comment]
bug been reported: see #17
