### ISSUE TITLE
Mjml import doesn't support mjml-style

### ISSUE THREAD

**Issue by blackbirdzzz** [artf/grapesjs-mjml#4]
When i import some code in the mjml import the <mj-style inline="inline">....</mj-style>
is transform into text and note into css

New bug detected : UndoManager for redo et undo don't work for mj-column and mj-section

**Comment by artf** [comment]
At the moment, don't plan to support `mjml-style`

**Comment by blackbirdzzz** [comment]
and for  (UndoManager for redo et undo don't work for mj-column and mj-section)

**Comment by artf** [comment]
Tried to undo/redo in the demo and it works, any error in console?

**Comment by CimattiConsulting** [comment]
Added mjml-style support. 
5dfeec2 #109
