### ISSUE TITLE
mj-image and mj-text in one mj-column

### ISSUE THREAD

**Issue by NorthstarTech** [artf/grapesjs-mjml#41]
In my application and the demo, components are disappearing from the canvas while still appearing in the code viewer and in any test emails I send. The html has the missing blocks as well. It happens most often when importing code in and when using images and text in the same column. 
I used the code below to reproduce the events on the demo. Please check and provide any hints as to where the issue may lie. I am looking at the rendering on the canvas to be the source of the problem. 

```javascript
<mjml>
  <mj-body>
    <mj-container>
      <mj-section>
        <mj-column>
          <mj-image width="400px" src="http://placehold.it/350x250/78c5d6/fff"/>
          <mj-text>Enter text in this block
          </mj-text>
        </mj-column>
        <mj-column>
          <mj-image width="400px" src="http://placehold.it/350x250/78c5d6/fff"/>
          <mj-text>Enter text in this block
          </mj-text>
        </mj-column>
      </mj-section>
    </mj-container>
  </mj-body>
</mjml>
```

**Comment by DmitryNek** [comment]
Found solution is to use closing tags for mj-image component.

`<mjml>
  <mj-body>
    <mj-container>
      <mj-section>
        <mj-column>
          <mj-image width="400px" src="http://placehold.it/350x250/78c5d6/fff"></mj-image>
          <mj-text>Enter text in this block</mj-text>
        </mj-column>
        <mj-column>
          <mj-image width="400px" src="http://placehold.it/350x250/78c5d6/fff"></mj-image>
          <mj-text>Enter text in this block</mj-text>
        </mj-column>
      </mj-section>
    </mj-container>
  </mj-body>
</mjml>`

**Comment by NorthstarTech** [comment]
I want to add the end tag  image while dragging the image block. I added the end tag while dragging but its not working. Anyone helps me that where should i place the image end tag?
Thanks

**Comment by DmitryNek** [comment]
I’ve added mj-image closing tags directly in block definitions. What is your use case to add them on the fly?

**Comment by NorthstarTech** [comment]
I also added in the block definition but when I drag it, it not viewing the end tag. Here is a code
![renderingissue](https://user-images.githubusercontent.com/33541046/34246625-3b799f12-e651-11e7-8f25-6646a3ce9788.png)

**Comment by DmitryNek** [comment]
Single mj-image block works well and components are not disappearing. I've proposed solution for blocks like on your first example.  

For example: 

<img width="378" alt="demo" src="https://user-images.githubusercontent.com/7448756/34246831-df5866d6-e638-11e7-80d9-ed9a325909b3.png">

Without closing mj-image tag on example above, mj-text and mj-button won't be rendered (actually they will be children of img in canvas).

**Comment by NorthstarTech** [comment]
yeah single mj-image is working fine for me. but when I drag mj-text or mj-button after mj-image in a single column, content will be disappear because of no ending tag of image. Is there any solution of placing ending tag image while dragging image component?

**Comment by DmitryNek** [comment]
> but when I drag mj-text or mj-button after mj-image in a single column, content will be disappear because of no ending tag of image

On my side mj-text or mj-button not disappear if drag them right after mj-image in a single column. Problem was only with complex block like on example above.

**Comment by NorthstarTech** [comment]
@DmitryNek  issue resolved. Thank u so much

**Comment by vizvasrj** [comment]
![Screenshot 2022-09-30 at 22-17-47 Email Editor](https://user-images.githubusercontent.com/83173578/193318663-0a6af7c8-4edc-4ebd-87f3-80251a5e02db.png)

```<mjml>
  <mj-body>
    <mj-section>
      <mj-column>
        <mj-divider border-color="tomato"></mj-divider>
        <mj-text align="center" font-size="20px">
          <div style="padding-top: 10px">
            <img style="border-radius: 20px;vertical-align:-9px" width="30px" src="https://cdna.artstation.com/p/assets/covers/images/054/433/594/smaller_square/lee-kimsan-lee-kimsan-1.jpg" /> <strong style="color: tomato">@</strong>hiroshi <strong>Followed You</strong>
            <div style="color: grey">June 25 th 2021</div>
            <hr style="width: 50%" />
          </div>
        </mj-text>

        <mj-text align="center" font-size="20px">
          <img style="border-radius: 20px;vertical-align:-9px" width="30px" src="https://cdna.artstation.com/p/assets/covers/images/054/366/420/smaller_square/morgane-malville-morgane-malville-morganemalville-morgana-thumbnail.jpg?1664374271" /> <strong style="color: tomato">@</strong>miamoto <strong>Followed You</strong>
        </mj-text>


      </mj-column>
    </mj-section>
  </mj-body>
</mjml>```
You can use this
