### ISSUE TITLE
Unable to make a layer visible after it has been hidden

### ISSUE THREAD

**Issue by padcom** [artf/grapesjs-mjml#42]
When playing around with layers I found that when I hide the Container layer it can't be made visible again.

Steps to reproduce:

1. Navigate to http://grapesjs.com/demo-mjml.html
2. Open Layer Manager
3. Expand "Body"
4. Click on the eye icon to the left next to "Container" - this makes the "Container" hidden
5. Click on the eye icon to the left next to "Container"

Expected result:

In point 5 the "Container" layer becomes visible again

Current result:

In point 5 the "Container" stays hidden

**Comment by michibat01** [comment]
@padcom @Granddevv 
for now there is no attribute in mjml 4 that hides an element, but perhaps there is a way to work directly on the html.

**Comment by artf** [comment]
This should be fixed in the latest release.
