### ISSUE TITLE
Canvas View issues

### ISSUE THREAD

**Issue by masfi** [artf/grapesjs-mjml#43]
Love your plugin, especially with the mjml. Other than known problematic email clients, it gives really responsive emails. The only things I am having an issue with is the view of items in the editor. The email sent out work great. There's no issue in the mjml being created. However the view of certain elements are strange like the container view. I included photos. This doesn't affect the actual email. I can provide more details if necessary. Please inform me of what you need. 

![2017-12-20_8-07-07](https://user-images.githubusercontent.com/34338501/34208569-e45f2dc2-e55c-11e7-9aa6-e661edde6f4c.jpg)
![2017-12-20_8-07-26](https://user-images.githubusercontent.com/34338501/34208573-e5ec6aec-e55c-11e7-9787-428bbd7d6c4f.jpg)

**Comment by artf** [comment]
Hi @masfi can you provide the template of your case or a live demo, because I can't reproduce it

**Comment by masfi** [comment]
Sure, I can provide the template code. I tested the mjml on the mjml live editor. It works fine there. I attempted it on the demo and worked fine but I thought the demo might not be up to date with this pull-request https://github.com/artf/grapesjs-mjml/pull/23? I couldn't tell if I was grasping for straws since this is the most javascript heavy work I have done so far. 


Btw, when I comment out the height line in mj-container, this issue doesn't occur anymore. However then there's the same issue of being unable to drop any components when the canvas is clear. 

```javascript
<mjml>
  <mj-body>
    <mj-container background-color="rgba(129,55,55,0.35)">
      <mj-section background-color="#E6F0FF">
        <mj-column>
        </mj-column>
      </mj-section>
      <mj-section>
        <mj-column>
          <mj-image src="http://placehold.it/350x250/78c5d6/fff">
          </mj-image>
          <mj-image src="http://placehold.it/350x250/78c5d6/fff">
          </mj-image>
        </mj-column>
        <mj-column>
          <mj-image src="http://placehold.it/350x250/78c5d6/fff">
          </mj-image>
          <mj-image src="http://placehold.it/350x250/78c5d6/fff">
          </mj-image>
        </mj-column>
      </mj-section>
      <mj-section>
        <mj-column>
          <mj-text>Enter text in this block 
          </mj-text>
        </mj-column>
        <mj-column>
          <mj-image src="http://placehold.it/350x250/78c5d6/fff">
          </mj-image>
        </mj-column>
      </mj-section>
      <mj-section>
        <mj-column>
          <mj-image src="http://placehold.it/350x250/78c5d6/fff">
          </mj-image>
          <mj-text>Enter text in this block 
          </mj-text>
        </mj-column>
      </mj-section>
      <mj-section>
        <mj-column>
          <mj-image src="http://placehold.it/350x250/78c5d6/fff">
          </mj-image>
          <mj-image src="http://placehold.it/350x250/78c5d6/fff">
          </mj-image>
        </mj-column>
        <mj-column>
          <mj-image src="http://placehold.it/350x250/78c5d6/fff">
          </mj-image>
          <mj-image src="http://placehold.it/350x250/78c5d6/fff">
          </mj-image>
        </mj-column>
      </mj-section>
      <mj-section>
        <mj-column>
          <mj-text>Start from here
          </mj-text>
        </mj-column>
      </mj-section>
      <mj-section background-color="#E6F0FF">
        <mj-column>
          <mj-text align="center">
            112233 aabbcc street, Anytown, GA, 30076
          </mj-text>
        </mj-column>
      </mj-section>
    </mj-container>
  </mj-body>
</mjml>
```

**Comment by DRoet** [comment]
I can't reproduce this on the latest version, it is true the demo page is sometimes a few versions behind. feel free to reopen a new issue if this is still a problem
