### ISSUE TITLE
Social Media Icon deletion

### ISSUE THREAD

**Issue by masfi** [artf/grapesjs-mjml#44]
![2017-12-20_8-11-31](https://user-images.githubusercontent.com/34338501/34208729-81dbfefe-e55d-11e7-89d9-d48bf5918926.jpg)
Currently, you have to type in what social media platform you want to use. I want to change that trait and either make it a multi-select or offer checkboxes or even a button. I can't find where the input for display is being set.

**Comment by artf** [comment]
You have to [extend](https://github.com/artf/grapesjs/wiki/Components#update-component-type) `mj-social` type and update with your custom [display trait](https://github.com/artf/grapesjs-mjml/blob/master/src/components.js#L766)
