### ISSUE TITLE
Setting MJ-container color prevents components from being dropped in view

### ISSUE THREAD

**Issue by masfi** [artf/grapesjs-mjml#45]
The issue occurs on the demo as well. If you set the container color, it appears like you can't drop any section blocks on the canvas. Content blocks like image and text are working. After further inspection in the mjml code, it's clear the components are being added to the template.  

Steps to reproduce
1. Any template works
2. set the container color
3. Add new blocks
4. Check code. The blocks will be there but they will not appear in editor.

**Comment by michibat01** [comment]
@masfi 
Fixed in v0.1.5 ab4f042
