### ISSUE TITLE
container removes on empty the canvas. 

### ISSUE THREAD

**Issue by NorthstarTech** [artf/grapesjs-mjml#47]
When I empty the canvas by clicking on the delete trash button, It also deletes the container and cant drag the elements on the canvas/editor.

**Comment by DRoet** [comment]
I can't reproduce this, please provide some code if it still happens

**Comment by suprtony87** [comment]
I've got this issue also...after clearing the canvas, can't add any new elements as the container is deleted as well.


		const commands = editor.Commands;
		commands.add('clearPage', editor => {
			editor.DomComponents.clear();
		  
		});


	var panelManager = editor.Panels;
	panelManager.addButton('options', {
	  id        : 'clearCanvas',
	  className : 'fa fa-trash',
	  title:'clear canvas',
	  command   : e => e.runCommand('clearPage'),
	  active    : false
	});
