### ISSUE TITLE
fromElement selfClosingTags

### ISSUE THREAD

**Issue by kickbk** [artf/grapesjs-mjml#48]
Try pasting this code in the page HTML, enable `fromElement: true` and reset the canvas.
```
<mjml>
  <mj-body>
    <mj-container>
      <mj-section>
        <mj-column>
          <mj-social facebook-content="Share" twitter-content="Tweet" google-content="+1" instagram-content="Share" linkedin-content="Share" pinterest-content="Pin it"/>
          <mj-text>Test</mj-text>
        </mj-column>
      </mj-section>
    </mj-container>
  </mj-body>
</mjml>
```

The MJML code remains the same but the HTML doesn't include the Text component.

A workaround is to close the mj-social tag like so:
```
...
          <mj-social facebook-content="Share" twitter-content="Tweet" google-content="+1" instagram-content="Share" linkedin-content="Share" pinterest-content="Pin it"></mj-social>
          <mj-text>Test</mj-text>
...
```
Then the Text component is visible when resetting the canvas.

**Comment by kickbk** [comment]
OK, so self closing tags is a known issue and a tough one at that. Currently seems like the only way around it is not to use self closing tags.

For us, there were two problematic entry points:
1. When importing MJML - core grapesjs-mjml
2. When using fromElement to load MJML - core grapesjs-mjml
3. When saving MJML - Our own action to save the MJML so that users may edit later

The work around we use was to run the MJML through a simple script that converts self closing tags to normal ones. See below.

```
// Get the MJML from the editor 
let selfMJMLOriginal = editor.getHtml();

// Parse and convert all self-closing tags.
function removeSelfClosingTags(selfClosingMJML) {
  let split = selfClosingMJML.split("/>");
  let convertedHtml = "";
  for (let i = 0; i < split.length - 1;i++) {
    let edsplit = split[i].split("<");
    convertedHtml += split[i] + "></" + edsplit[edsplit.length - 1].split(" ")[0] + ">";
  }
  return convertedHtml + split[split.length-1];
}

// Run the MJML through the script
let outputMJML = removeSelfClosingTags(selfMJMLOriginal)
```

You can apply the same script to the import function in command-import-mjml.js

```
btnImp.onclick = () => {
    let selfMJMLOriginal = codeViewer.editor.getValue();
    editor.DomComponents.getWrapper().set('content', '');

    // Script to parse and close all self closing tags.
    function removeSelfClosingTags(selfClosingMJML) {
      //See above
    }

    let code = removeSelfClosingTags(selfMJMLOriginal)
    editor.setComponents(code.trim());
    editor.Modal.close();
};
```

Open to more elegant solutions.

**Comment by DRoet** [comment]
closing this as we already have an issue for self-closing tags: https://github.com/artf/grapesjs-mjml/issues/149
