### ISSUE TITLE
Edit MJML code

### ISSUE THREAD

**Issue by HLFH** [artf/grapesjs-mjml#5]
Hi,

Can we edit MJML code using GrapesJS-MJML or only view the code?
If not, can you support the ability to edit the MJML source code?

![editcode](https://user-images.githubusercontent.com/2359059/28413792-27dfdee8-6d49-11e7-8d4d-6b44b64f37f6.PNG)

**Comment by artf** [comment]
Not directly, but you can copy the code and use it in the importer

**Comment by HLFH** [comment]
Ok so you close even if a real editing feature is needed.
