### ISSUE TITLE
mj-body isn't stylable but the style manager still contains options for it. 

### ISSUE THREAD

**Issue by masfi** [artf/grapesjs-mjml#52]
I am trying to remove the decorations tab from the style manager. Is there a default set that I have to override? I used the unstylabe and stylable properties in the component. It had no effect. Am I missing something?
![body-background image](https://user-images.githubusercontent.com/34338501/34586574-84e63486-f172-11e7-9297-ec5a77fec7a0.jpg)

**Comment by AliErdin** [comment]
same issue

**Comment by DRoet** [comment]
Only the width/backgroud color is stylable for mj-body since that is was is supported by `mjml`, could you try the latest version and reopen an issue if this is still happening?
