### ISSUE TITLE
load is not a function

### ISSUE THREAD

**Issue by jfrux** [artf/grapesjs-mjml#58]
I have grapejs installed and everything.
But when I add the option `plugins: ['gjs-mjml']` it throws this error.

I've confirmed that grapejs is loaded and it exists in `grapejs.plugins.getAll();`

Having trouble understanding the disconnect?

**Comment by joshuairl** [comment]
Take that back, it's not doing it in Chrome but it's doing in Electron only... :-/ 
`/cry`
haha

Sorry - odd that it's not compatible tho... but digging a bit deeper and will keep you posted.

**Comment by technophilic** [comment]
Hey! @jfrux  Were you successful in getting this to work?

**Comment by artf** [comment]
TBH I'd expect it to work in Electron exactly as in Chrome, probably the plugin is not loaded correctly.

ps. the plugin name now is `grapesjs-mjml`
