### ISSUE TITLE
Attributes on Dragging Components

### ISSUE THREAD

**Issue by NorthstarTech** [artf/grapesjs-mjml#60]
When I dragging the mj-text component, their attributes are removing on drag to canvas.
![error](https://user-images.githubusercontent.com/33541046/35568779-e7a7be9a-05eb-11e8-941b-46e52cbdbcee.png)

data-gjs-editable="false" <= (this will remove on drag to canvas).
How should I fix this issue? I need the custom attributes while dragging but it removes.

**Comment by artf** [comment]
This should be fixed in the latest release.
