### ISSUE TITLE
Issue with mj-container background color

### ISSUE THREAD

**Issue by IrinaCodixis** [artf/grapesjs-mjml#62]
Hi,
I am experiencing a problem with mj-container. Right after setting a new background color for a mj-container from the style manager, I cannot create new sections. Looks like mjml code is being generated, but fails to update the canvas.
It is reproducible from your demo. 
Steps to reproduce:
- Select mj-container
- Change background color
- Drag and drop a new "1 Column" block. (Also fails with "2 Columns" and "3 Columns")
Thanks.

**Comment by kuldeepcis** [comment]
@IrinaCodixis can you please update me for this?

Thanks in advance.
