### ISSUE TITLE
Related demo project

### ISSUE THREAD

**Issue by tvkit** [artf/grapesjs-mjml#64]
Is it possible to get access to the project/repo for the related grapesjs-mjml [demo](http://grapesjs.com/demo-mjml.html) ?

I'm attempting to add in the ckeditor plugin following the demo's index.html page, but things are not going smoothly.  For example, I grabbed 

` <script src="./js/ckeditor/ckeditor.js"></script>`

but other missing dependencies were reported in the debug console.

**Comment by DRoet** [comment]
setting up the ckeditor is more related to the grapejs project, unfortunately the demo project is not hosted in this repository so I can't do much to help
