### ISSUE TITLE
Upgrade to mjml4

### ISSUE THREAD

**Issue by sergeysova** [artf/grapesjs-mjml#65]
Now mjml@3 is legacy https://github.com/mjmlio/mjml/tree/3.3.x

**Comment by arthurkatz** [comment]
Would be really good upgrade to mjml4

**Comment by anand-gopinath** [comment]
@sergeysova @arthurkatz I just forked the repo and upgraded to latest MJML version 4.0.0-beta and i got some errors like [https://github.com/mjmlio/mjml/issues/928](url)

**Comment by arthurkatz** [comment]
@anand-gopinath then the alternative is to use MJML API right ?

**Comment by anand-gopinath** [comment]
Yeah...I asked the team to for other solutions as well

**Comment by frasza** [comment]
@artf Hello. Would it be possible to update to mjml 4?

**Comment by artf** [comment]
@frasza no it's not possible because mjml 4 has dropped support for rendering in browser https://github.com/mjmlio/mjml/issues/928

**Comment by bures** [comment]
I would like to reopen this issue as I have a solution to webpack mjml 4. Please see https://github.com/artf/grapesjs-mjml/issues/73#issuecomment-437543265

**Comment by bures** [comment]
One addition. To make it all simpler, I packaged MJML4 suitable for browser here: https://www.npmjs.com/package/mjml4-in-browser

**Comment by artf** [comment]
> I would like to reopen this issue as I have a solution to webpack mjml 4.

That issue 73 is open so let's keep talking there
