### ISSUE TITLE
invalid target position in latest version (0.0.27)

### ISSUE THREAD

**Issue by ahmadcore** [artf/grapesjs-mjml#78]
hii, iuse this plugin wiht version 0.0.27 (latest), but when i drag and drop control i found warning `Invalid target position: Target collection not found, Target is not droppable, accepts [undefined], Component not draggable, acceptable by [undefined] Sorter.js:1019:6 `

i follow this [#21](https://github.com/artf/grapesjs-mjml/issues/21), but i think it suitable for old version not for new version

here my code:
header
`<link rel="stylesheet" type="text/css" href="<?=base_url('assets/plugins/grapejs/css/grapes.min.css?v0.14.27')?>" />
    <link rel="stylesheet" type="text/css" href="<?=base_url('assets/plugins/grapejs/css/material.css')?>" />
    <link rel="stylesheet" type="text/css" href="<?=base_url('assets/plugins/mjml/grapesjs-mjml.css')?>" />`

body
`<div id="gjs"></div>

    <script type="text/javascript" src="<?=base_url('assets/plugins/grapejs/grapes.min.js?v0.14.27')?>"></script>
    <script type="text/javascript" src="<?=base_url('assets/plugins/grapejs/aviary.js')?>"></script>
    <script type="text/javascript" src="<?=base_url('assets/plugins/grapejs/mjml/grapesjs-mjml.min.js')?>"></script>
    <script type="text/javascript" src="<?=base_url('assets/plugins/grapejs/grapesjs-aviary.min.js')?>"></script>
    
    <script type="text/javascript">
        var images = [];
        var editor = grapesjs.init({
            clearOnRender: true,
            storageManager: {id: 'gjs-mjml-'},
            assetManager: {
                assets: images,
                upload: 0,
                uploadText: 'Not allowed',
            },
            fromElement: true,
            container : '#gjs',
            plugins: ['gjs-mjml']/*,
            pluginsOpts: {
                'gjs-preset-newsletter': {
                    modalTitleImport: 'Import template',
                    // ... other options
                }
            }*/
        });`

**Comment by Jonatasmz** [comment]
Confirm it's not working anymore.

**Comment by artf** [comment]
Fixed in https://github.com/artf/grapesjs-mjml/releases/tag/v0.0.31
