### ISSUE TITLE
Adding tables?

### ISSUE THREAD

**Issue by ErnestsMillers** [artf/grapesjs-mjml#8]
This is not really an issue. I am trying to do it myself, but is it possible to get mjml-table support anywhere soon? It's quite confusing because of td and tr. There really is no documentation about creating blocks for grapesjs-mjml and I am quite stuck when it comes to getting to understand all the conversion between html and mjml.

Please, that would be great help. If I make this work myself I will make pull request. :)

**Comment by artf** [comment]
Hi @ErnestsMillers honestly I don't think I'm gonna support tables soon. The best I can do for now is to tell you to check https://github.com/artf/grapesjs-mjml/blob/master/src/components.js this is where mjml components are created. Try to see how other components are implemented, but it's not too much different from [defining a new Component](https://github.com/artf/grapesjs/wiki/Components#define-new-component), you just have to extend `coreMjmlModel` and `coreMjmlView`

**Comment by ErnestsMillers** [comment]
I have been trying to add tables functionality for days but without any success. First of all I don't understand why tr's and td's just gets deleted even if I add that to markup. Adding blocks is easy but when it comes to components.js I can't figure out how to properly render things. I am posting my code below and if I can get any additional guidelines it would be a lifesaver.

blocks.js
```
bm.add('mj-table', {
    label: 'Table',
    content: `<mj-table><tr><td>he</td></tr></mj-table>`,
    attributes: {
      'data-type': 'mj-table',
    },
  });

  bm.add('tr', {
    label: 'Tr',
    content: `<tr><td>Test</td></tr>`,
    attributes: {
      'data-type': 'tr',
    },
  });

   bm.add('td', {
    label: 'Td',
    content: `<td>Test</td>`,
    attributes: {
      'data-type': 'td',
    },
  });
```
components.js
```
// mj-table
  domc.addType('Table', {
    model: defaultModel.extend(Object.assign({}, coreMjmlModel, {
      defaults: Object.assign({}, defaultModel.prototype.defaults, {
        'custom-name': 'Table',
        draggable: '[data-type=mj-column]',
        highlightable: true,
        stylable: [
          // Dimension
         'width'
          // Typography
          // Decorations
        ],
        style: {
          'width': '100%'
        },
      }),
    }), {
      isComponent(el) {
        if (el.tagName == 'MJ-TABLE') {
          return {
            type: 'Table',
          };
        }
      },
    }),
    view: defaultView.extend(Object.assign({}, coreMjmlView, {
      tagName: 'tr',

      attributes: {
        style: 'pointer-events: all; display: table; width: 100%',
      },

    })),
  });

  // tr
  domc.addType('Tr', {
    model: defaultModel.extend(Object.assign({}, coreMjmlModel, {
      defaults: Object.assign({}, defaultModel.prototype.defaults, {
        'custom-name': 'Tr',
        draggable: '[data-type=mj-table]',
        highlightable: true,
        stylable: [
          // Dimension
          // Typography
          // Decorations
        ],
        style: {
        },
      }),
    }), {
      isComponent(el) {
        if (el.tagName == 'tr') {
          return { 
            type: 'tr',
          };
        }
      },
    }),
    view: defaultView,
  });

   // td
  domc.addType('Td', {
    model: defaultModel.extend(Object.assign({}, coreMjmlModel, {
      defaults: Object.assign({}, defaultModel.prototype.defaults, {
        'custom-name': 'Tr',
        draggable: '[data-type=tr]',
        highlightable: true,
        stylable: [
          // Dimension
          // Typography
          // Decorations
        ],
        style: {
        },
      }),
    }), {
      isComponent(el) {
        if (el.tagName == 'td') {
          return {
            type: 'td',
          };
        }
      },
    }),
    view: defaultView,
  });
```

**Comment by artf** [comment]
@ErnestsMillers just by quick looking I've seen this:
```js
domc.addType('Td', { // <-- decalring `Td`
...
     return {
            type: 'td', // returning `td`, so the type ID is not the same
          };
// same for tr
```

**Comment by ErnestsMillers** [comment]
Hi, @artf. Thank you, I noticed it some time ago and already fixed it. The main issue I am having, I don't understand where the tr, td disappears from markup. Mjml-table works together with standard tr's and td's. But somehow they disappear both in view code and when I inspect editor. As you can see in blocks.js The way I added component. I believe the best approach is to place the table element in tr as any other element, then making a td and then table which will contain the actual tr's td's for table.

[Imgur](http://i.imgur.com/7dnZSik.png)
[Imgur](http://i.imgur.com/rrY4AO8.png)

blocks.js is the same.
components.js looks like this:
```
// mj-table
  domc.addType('mj-table', {
    model: defaultModel.extend(Object.assign({}, coreMjmlModel, {
      defaults: Object.assign({}, defaultModel.prototype.defaults, {
        'custom-name': 'Table',
        draggable: '[data-type=mj-column]',
        highlightable: true,
        stylable: [
        ' height', 'font-style', 'font-size', 'font-weight', 'font-family', 'color',
          // Dimension
         'width'
          // Typography
          // Decorations
        ],
        style: {
          'width': '100%',
          'font-size': '14px'
        },
      }),
    }), {
      isComponent(el) {
        if (el.tagName == 'MJ-TABLE') {
          return {
            type: 'mj-table',
          };
        }
      },
    }),
    view: defaultView.extend(Object.assign({}, coreMjmlView, {
      tagName: 'tr',

      attributes: {
        style: 'pointer-events: all; display: table; width: 100%; user-select: none;',
        'data-type': 'mj-table',
      },

      getChildrenSelector() {
        return 'td > table';
      },

      getMjmlTemplate() {
        return {
          start: `<mjml><mj-body><mj-column>`,
          end: `</mj-column></mj-body></mjml>`,
        };
      },
    })),
  });

  // tr
  domc.addType('tr', {
    model: defaultModel.extend(Object.assign({}, coreMjmlModel, {
      defaults: Object.assign({}, defaultModel.prototype.defaults, {
        'custom-name': 'Tr',
        draggable: '[data-type=mj-table]',
        highlightable: true,
        stylable: [
          // Dimension
          // Typography
          // Decorations
        ],
        style: {
          'width': '100%'
        },
      }),
    }), {
      isComponent(el) {
        if (el.tagName == 'TR') {
          return { 
            type: 'tr',
          };
        }
      },
    }),
    view: defaultView.extend(Object.assign({}, coreMjmlView, {
      tagName: 'tr',
      attributes: {
        'data-type': 'tr',
      },
    })),
  });

   // td
  domc.addType('td', {
    model: defaultModel.extend(Object.assign({}, coreMjmlModel, {
      defaults: Object.assign({}, defaultModel.prototype.defaults, {
        'custom-name': 'Td',
        draggable: '[data-type=tr]',
        highlightable: true,
        stylable: [
          // Dimension
          // Typography
          // Decorations
        ],
        style: {
          'width': '100%'
        },
      }),
    }), {
      isComponent(el) {
        if (el.tagName == 'TD') {
          return {
            type: 'td',
          };
        }
      },
    }),
    view: defaultView.extend(Object.assign({}, coreMjmlView, {
      tagName: 'td',

      attributes: {
        'data-type': 'td',
      },
    })),
  });
```

**Comment by artf** [comment]
I'll try to add it by myself and will let you know

**Comment by NorthstarTech** [comment]
Was a fix found for this issue? Since it is closed.

**Comment by sachinbhise76** [comment]
What is changes in @ErnestsMillers  mentioned code.
Please post code

**Comment by jmadureira** [comment]
@ErnestsMillers I don't know if you are still interested in this issue but I noticed that the reason that `<tr>` and `<td>` aren't appearing is because they aren't being parsed at all. If you noticed the calls to the `isComponent` those tags are never checked. My guess is that the issue may be related with grapesjs itself.

**Comment by jcolla-holla** [comment]
Were you ever to get this to work successfully @ErnestsMillers ?

**Comment by mykolakecha** [comment]
Are there any updates regarding the issue? I've spend 2 days trying to get this working, but no luck for now...

**Comment by CrayD** [comment]
The problem is that **grapesjs** uses [DOMParser.parseFromString()](https://developer.mozilla.org/en-US/docs/Web/API/DOMParser/parseFromString) with second argument(MIME type) "text/html" by default and  `<mj-table><tr><td>Test</td></tr></mj-table>` is not a valid html, that's why the tr, td tags are cleared. As a solution you can configure it using **parser.htmlType** option:
```js
grapesjs.init({
          ...
          parser: {
              htmlType: 'text/xml'
          },
          ...
});
```
It's not documented (I haven't found it in docs), so I'm not sure how it will affect other functionality.

**Comment by CrayD** [comment]
The problem is that **grapesjs** uses [DOMParser.parseFromString()](https://developer.mozilla.org/en-US/docs/Web/API/DOMParser/parseFromString) with second argument(MIME type) "text/html" by default and
`<mj-table><tr><td>Test</td></tr></mj-table>` is not a valid html, that's why the tr, td tags are cleared.
Solution that works for dev version is to pass option `parser.htmlType`, but this option is not available in latest version **0.17.22**, probably will become available on the next release.

```js
grapesjs.init({
          ...
          parser: {
              htmlType: 'text/xml'
          },
          ...
});
```

**Comment by emilsedgh** [comment]
The reason this doesn't work is this:

Grapesjs uses browsers internal html parser in order to parse an html to a tree.

However, for browsers, `mj-table` is not a valid element. Thus, they wont allow `tr` to be inside an `mj-table`.

The root cause is similar to  #149. And the solution for both would be Grapesjs either using a different dom parser (eg DOMParser api) which would properly parse non-html code like mjml, or at least making it possible to use a different parser so plugins like grapesjs-mjml can do that on their own.

**Comment by artf** [comment]
@emilsedgh yeah it's correct but, you are actually already able to change the HTML parser type on init (here the default [config](https://github.com/artf/grapesjs/blob/dev/src/parser/config/config.js)).
```js
grapesjs.init({
 // ...
 parser: { htmlType: 'text/xml' } // text/xml won't change the HTML 
})
```
One thing worth noting, we have to update [isComponentType](https://github.com/artf/grapesjs-mjml/blob/a595f11926b17e978ef0cb75cc4fc82cf9b8cf7b/src/components/utils.js#L3) in mjml components, with XML parser, tagName is not uppercased.
