### ISSUE TITLE
Default properties not being applied

### ISSUE THREAD

**Issue by kuldeepcis** [artf/grapesjs-mjml#80]
When we load the editor and drag a text block.it has some padding which is not reflected in the editor.how can we reflect those properties?

**Comment by JKirschbaumTG** [comment]
Hello, we have noticed a similar issue with the button block. When I drag a new button, it is center-aligned. When I go into the styling, it says that it's right-aligned. When I click "center-align" it stays centered, and when I click "right-align" again, it right-aligns. 

I have also seen some odd behavior around the line height. If I drag a new text block, then increase the font size to the point where the text wraps onto a new line, the line height doesn't adjust correctly. If I change the line height to something specific (certain number of pixels, etc), then change it back to just "normal", this resolves the problem. Is this a related issue, or should that be a separate ticket?

Thanks again for all of the excellent work you do on this project!

**Comment by Felix-Indoing** [comment]
Any update on this? Did you get workaround this problem?

**Comment by DRoet** [comment]
Please open up a new issue with reproduction if this is still happening in the latest version (0.1.17+)
