### ISSUE TITLE
Navbar component

### ISSUE THREAD

**Issue by matteod** [artf/grapesjs-mjml#81]
Hello, 
 is it possible to add navbar component? How can I extend block elements?

**Comment by larsdecker** [comment]
@matteod 
I have started the implementation for some missing elements of mjml 4 in a new branch at
https://github.com/larsdecker/grapesjs-mjml/tree/feature/newElements

It is not finished yet, but the basic structure is there. Maybe you can help us.

**Comment by CimattiConsulting** [comment]
@matteod @larsdecker 
Implemented it #109

**Comment by artf** [comment]
https://github.com/artf/grapesjs-mjml/releases/tag/v0.1.8 released
