### ISSUE TITLE
Add padding control to Column

### ISSUE THREAD

**Issue by kickbk** [artf/grapesjs-mjml#83]
hey @artf I realize this project is not prioritized, partly of MJML 4 not playing nicely.
I would switch to the newsletter project had it been producing the same "device" compatibe html as your MJML plugin does. Last I tested it was not as compatible.

In the meantime, I am trying to get the best out of this one and I noticed a slight problem adjusting the padding for columns.

My setup:
I load the original MJML files from node_modules and have my own MJML component that extends it (based on yours).

I am able to show the padding controls by adding to my component
```
model: defaultModel.extend({ ...coreMjmlModel,

      defaults: {
          ...
          stylable: [
              ...
              'padding', 'padding-top', 'padding-left', 'padding-right', 'padding-bottom'
	  ],
	  style: {
		'padding-top': '10px',
		'padding-bottom': '10px'
	  },
      ...
```

However changing the properties has no effect.

Inside getTemplateFromMjml I printed console.log("htmlOutput", htmlOutput); and noticed I get "Attribute padding... and id are illegal"
I opened mjml-column original and added padding to 
```
var defaultMJMLDefinition = {
  attributes: {
```

and in other parts of this file.
I now don't get the illegal attribute notice, but it still doesn't work.

I'm a little lost. Would you mind giving me some pointers?

Cheers

**Comment by kickbk** [comment]
So the problem mainly was that the component overwrites the editable attributes:
```
attributes: {
        'data-type': 'mj-column',
        style: 'pointer-events: all;' +
          (clmPadd ? `padding: ${clmPadd};` : ''),
      },
```

By removing `(clmPadd ? `padding: ${clmPadd};` : '')` it grabs the styles from the editor.

By the way, @art, in the component there is an error:
```
return {
        start: `<mjml><mj-body><mj-container>`,
	end: `${addColmn}</mj-container></mj-body></mjml>`,
        };

```
If I'm not mistake, it should be nested inside mj-section and not mj-container. Nesting inside mj-container is illegal for that component and returns an error, even though it is hidden. 
You can see the error by printing the htmlOutput inside getTemplateFromMjml()

It also complains about ID being an illegal error. 
I edited the mjml component by adding it there and the error goes away.

**Comment by DRoet** [comment]
the first point should be fixable by overwriting `opt.columnsPadding` , second point is already fixed in the latest release

closing this for now, really appreciate all your findings (I know its a bit late)
