### ISSUE TITLE
MJ_RAW in grapesJS MJML

### ISSUE THREAD

**Issue by NorthstarTech** [artf/grapesjs-mjml#84]
is mj-raw will works for grapesJS MJML? If yes then how can I achieve this? Basically I want to add the html code inside my MJML. Is it possible in grapesJS MJML editor??

Thanks. Waiting for feedback and suggestions.

**Comment by kickbk** [comment]
You could add the `sourcedialog` plugin for CKeditor

**Comment by artf** [comment]
`mj-raw` is not included, but I think you could even use this plugin: https://github.com/artf/grapesjs-custom-code Just remember that your HTML will be rendered in email clients
