### ISSUE TITLE
Changing the width of the container breaks Blocks DnD

### ISSUE THREAD

**Issue by bonejon** [artf/grapesjs-mjml#88]
Hi,

We're reviewing the functionality of MJML for designing email template, however have a small issue with changing the default width of the mjml-container element.

Steps to reproduce:
Use the main demo: https://grapesjs.com/demo-mjml.html
Change the mjml-container width to 80%
Attempt to drag and drop any container object, such as columns.

Observations, the highlight appears indicating where the object can be dropped, however on drop nothing happens. There are also no errors in the console.

This behaviour can be observed no matter what value you enter for the width, including the default of 600px.

Would appreciate any thoughts on this issue,.

**Comment by larsdecker** [comment]
It is fixed with version [v0.1.8](https://github.com/artf/grapesjs-mjml/releases/tag/v0.1.8)
