### ISSUE TITLE
Edit text issue: Once clicked, it loses focus

### ISSUE THREAD

**Issue by oguimbal** [artf/grapesjs-mjml#90]
First, thanks for this plugin :)

That said, I dont understand why nobody reported this before:

 (the screencast below has been shot [from the demo](https://grapesjs.com/demo-mjml.html))
![anim](https://user-images.githubusercontent.com/8973947/51540050-c3f24a00-1e55-11e9-8844-20f56468b0d4.gif)

When double-clicking on text, it opens the text editor (as expected).
However, if you try to click elsewhere to move your cursor, the editor loses focus, and the line below prevents it from receiving further pointer events

https://github.com/artf/grapesjs-mjml/blob/e887e58602fc2243b6ad59d04c4cc1d8bcb22cb0/src/components/index.js#L218

... which is quite annoying from a user perspective.

What is the use of these lines, and can they be removed/fixed ?

Thanks !

**Comment by kickbk** [comment]
I already posted about it and just added a solution: https://github.com/artf/grapesjs/issues/1649

**Comment by oguimbal** [comment]
Thanks
