### ISSUE TITLE
Export to MJML instead of HTML

### ISSUE THREAD

**Issue by david-vde** [artf/grapesjs-mjml#91]
Hello

How to get the MJML code instead of the HTML code?

Ideally I would like to add an export button for MJML source instead of HTML.

Thank you

**Comment by kickbk** [comment]
You get the MJML with `editor.getHtml();` This will return your MJML code. You can try it in the console to see the result.
Read the getting started docs to understand how to add a button. It's very easy.

**Comment by david-vde** [comment]
It is what I'm trying to do and I get HTML not MJML.

See here : https://grapesjs.com/demo.html

grapesjs.editors[0].getHtml();
"<div class="row"><div class="cell"></div></div>"

Maybe I'm doing it wrong ?

**Comment by noogen** [comment]
@david-vde From the output, it doesn't look like you have any mjml component? Those look like basic row/column component.  Demonstrate that it work, simply:

1. Go to the demo: https://grapesjs.com/demo-mjml.html 
2. Inspect element, switch to console tab, and type: grapesjs.editors[0].getHtml()
3. see the mjml now?   working fine for me.

**Comment by david-vde** [comment]
Indeed it works thank you very much
