### ISSUE TITLE
Styles text inside buttons

### ISSUE THREAD

**Issue by kickbk** [artf/grapesjs-mjml#93]
I would like to allow styling of button text using ckeditor.
When I import mjml code with a button component like so:
```
<mj-button href='...'>
	<em>Hello</em>
</mj-button>
```
It creates this html inside the canvas:
`<a href="..." style="..." ...>
	<em data-gjs-type="text" data-highlightable="1">Hello</em>
</a>`

I suspect that the model considers the styled text as a text component by itself. Not sure how it gets to decide that... 

These attributes are set for every component inside the button, and it causes it to act funny.

When I go to the mjml core view and comment out `this.renderContent(); ` all the content is gone. Button content is gone, but NOT the text above. It's like mjml doesn't consider the Hello text to be the content of the component. Which makes me think it creates the text inside the button as a new and separate component.

Any ideas how to make the text inside the button part of the button element?

**Comment by DRoet** [comment]
I don't think we can easily provide a way to mix html and mjml code, however I added a way to style buttons as italic (the font-style property was missing)
