### ISSUE TITLE
Image resize percentage not working

### ISSUE THREAD

**Issue by IceCrystal0k** [artf/grapesjs-mjml#96]
Steps to reproduce:
in [Mjml Demo page](https://grapesjs.com/demo-mjml.html)
Select the image with the car.
In the Dimension tab, change width value to :  80% (or 80 and then select the percentage from the dropdown in the right).
The image size will be set to 80px, not 80% of the original width.

**Comment by DRoet** [comment]
should be fixed in the latest release (0.1.17)
