### ISSUE TITLE
Mjml plugin export

### ISSUE THREAD

**Issue by dabuionut** [artf/grapesjs-mjml#97]
Hi all,
I have a question I implemented the mjml plugin to my app but i have one issue when i try to export the code i have only the mjml code , but in the demo i saw that is also the html code how can i get this thing also to work for me .
And another issue when the canvas is blank i have this error 
 Error: [MJMLError] EmptyMJMLError: No root "<mjml>" or "<mj-body>" found in the file, or "<mj-body>" doesn't contain a child element.
And when i try to drag a block on the canvas is not working only when i have some code imported

**Comment by DRoet** [comment]
You should be able to export the html using `editor.runCommand('mjml-get-code').html`. as for the other issue I'm not sure if I understand what is happening. please check the latest release if this still occurs and create a new issue including a full code example.
