### ISSUE TITLE
Unable to add link to text

### ISSUE THREAD

**Issue by mathieuk** [artf/grapesjs-mjml#98]
When using grapesjs-mjml with the built-in RTE (read: not CKEditor) it seems impossible to add a link to text. 

**Steps to problem:**
* Open grapesjs-mjml with builtin RTE
* Add a text block with some text.
* Activate the builtin-RTE and try to add a link to some text

**Expected behaviour:**
* Link gets created
* Sidebar switches to component attributes pane which shows a field for 'HREF'.

**Actual behaviour:**
* Link gets created
* RTE editor gets disabled
* No switch to component attributes pane

I'm also unable to update the HREF attribute by selecting an existing link as the RTE editor gets disabled when you switch cursor focus over to the sidebar.

I've determined that this problem does not occur in regular grapesjs without the grapesjs-mjml plugin. 

@artf I'm happy to look into this myself but perhaps you have tips about where to look ?

**Comment by izaa** [comment]
@mathieuk did you solve this?

**Comment by AliErdin** [comment]
I have the same issue.

**Comment by larsdecker** [comment]
Yes, i can confirm that it not working correctly. I can see the href under the components settings.
But it was not written to the mjml or the final html code.

![Bildschirmfoto 2019-10-23 um 10 20 32](https://user-images.githubusercontent.com/1968186/67372899-f06efa00-f57e-11e9-94db-b5cafb9c0e72.png)

When i have time, i will look at the code and try to fix this issue.

**Comment by simdrouin** [comment]
I was able to fix this with a cloned version locally, it turns out if I comment out the `disableEditing` function in `src/components/Text.js`, as well as removing the reference to this function in the `extendFnView` array at the top of the same file, this solves the `Href` issue of links inside `Text` components.  So far I haven't seen any unwanted side-effects of this removal.
