### ISSUE TITLE
mj-container remove since MJML 4.0

### ISSUE THREAD

**Issue by freliberty** [artf/grapesjs-mjml#99]
The component `mj-container `[was remove since](https://fr.mailjet.com/blog/news/mjml-birthday/) [MJML 4.0.](https://github.com/mjmlio/mjml/tree/3.3.5) So we can't convert ours template create with grapsjs. And we can't create template grapesjs without mj-container.
Thank You.

**Comment by Jogai** [comment]
This plugin is still using mjml 3 I believe

**Comment by CimattiConsulting** [comment]
@freliberty @Jogai  #105
